// Homebrew cask template for the desktop DMG. goreleaser's OSS cask pipe can
// only publish artifacts it built and checksummed itself, so the desktop app
// cask is rendered here and pushed to the tap by publish-desktop-cask.mjs.
// Pure function only, so the generated Ruby stays unit-testable.

const VERSION_PATTERN = /^\d+\.\d+\.\d+$/;
const SHA256_PATTERN = /^[0-9a-f]{64}$/;

/**
 * Render Casks/agentico-desktop.rb for one release. The URL is derived from
 * the version tag; the artifact name is fixed by electron-builder config
 * (Agentico-mac-universal.dmg).
 */
export function renderDesktopCask({ version, sha256 }) {
  if (!VERSION_PATTERN.test(version)) {
    throw new Error(`cask version must be MAJOR.MINOR.PATCH, got ${JSON.stringify(version)}`);
  }
  if (!SHA256_PATTERN.test(sha256)) {
    throw new Error(`cask sha256 must be a lowercase hex digest, got ${JSON.stringify(sha256)}`);
  }
  return `# Generated by desktop/scripts/publish-desktop-cask.mjs — do not edit by hand.
cask "agentico-desktop" do
  version "${version}"
  sha256 "${sha256}"

  url "https://github.com/doordash-oss/agentic-orchestrator/releases/download/v#{version}/Agentico-mac-universal.dmg"
  name "Agentico"
  desc "Desktop-first parallel agentic coding orchestrator"
  homepage "https://github.com/doordash-oss/agentic-orchestrator"

  # The app updates itself in place through its verified in-app updater;
  # \`brew upgrade --greedy\` still refreshes it from the tap.
  auto_updates true

  app "Agentico.app"

  # The DMG is not yet Developer ID-signed or notarized; Homebrew quarantines
  # its downloads, and Gatekeeper refuses quarantined unsigned apps. Remove
  # once releases are notarized.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Agentico.app"]
  end

  zap trash: [
    "~/Library/Application Support/Agentico",
    "~/Library/Caches/com.doordash.agentico",
    "~/Library/Preferences/com.doordash.agentico.plist",
    "~/Library/Saved Application State/com.doordash.agentico.savedState",
  ]
end
`;
}
