// Copyright 2026 DoorDash, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package server

import (
	"time"

	config "github.com/doordash-oss/agentic-orchestrator/internal/config"
)

const (
	BearerAuthScopes     bearerAuthContextKey     = "bearerAuth.Scopes"
	SseAccessTokenScopes sSEAccessTokenContextKey = "sseAccessToken.Scopes"
)

// Defines values for AutomaticReviewStateMode.
const (
	AutomaticReviewStateModeDefault  AutomaticReviewStateMode = "default"
	AutomaticReviewStateModeDisabled AutomaticReviewStateMode = "disabled"
	AutomaticReviewStateModeEnabled  AutomaticReviewStateMode = "enabled"
)

// Valid indicates whether the value is a known member of the AutomaticReviewStateMode enum.
func (e AutomaticReviewStateMode) Valid() bool {
	switch e {
	case AutomaticReviewStateModeDefault:
		return true
	case AutomaticReviewStateModeDisabled:
		return true
	case AutomaticReviewStateModeEnabled:
		return true
	default:
		return false
	}
}

// Defines values for AutomaticReviewStateSource.
const (
	Feature AutomaticReviewStateSource = "feature"
	Global  AutomaticReviewStateSource = "global"
)

// Valid indicates whether the value is a known member of the AutomaticReviewStateSource enum.
func (e AutomaticReviewStateSource) Valid() bool {
	switch e {
	case Feature:
		return true
	case Global:
		return true
	default:
		return false
	}
}

// Defines values for FeatureConfigAutomaticReviewMode.
const (
	FeatureConfigAutomaticReviewModeDefault  FeatureConfigAutomaticReviewMode = "default"
	FeatureConfigAutomaticReviewModeDisabled FeatureConfigAutomaticReviewMode = "disabled"
	FeatureConfigAutomaticReviewModeEnabled  FeatureConfigAutomaticReviewMode = "enabled"
)

// Valid indicates whether the value is a known member of the FeatureConfigAutomaticReviewMode enum.
func (e FeatureConfigAutomaticReviewMode) Valid() bool {
	switch e {
	case FeatureConfigAutomaticReviewModeDefault:
		return true
	case FeatureConfigAutomaticReviewModeDisabled:
		return true
	case FeatureConfigAutomaticReviewModeEnabled:
		return true
	default:
		return false
	}
}

// Defines values for FeatureConfigInputNotifications.
const (
	Default FeatureConfigInputNotifications = "default"
	Enabled FeatureConfigInputNotifications = "enabled"
	Muted   FeatureConfigInputNotifications = "muted"
)

// Valid indicates whether the value is a known member of the FeatureConfigInputNotifications enum.
func (e FeatureConfigInputNotifications) Valid() bool {
	switch e {
	case Default:
		return true
	case Enabled:
		return true
	case Muted:
		return true
	default:
		return false
	}
}

// Defines values for PermissionAnswerRequestDecision.
const (
	AllowOnce     PermissionAnswerRequestDecision = "allow_once"
	AllowRemember PermissionAnswerRequestDecision = "allow_remember"
	Deny          PermissionAnswerRequestDecision = "deny"
)

// Valid indicates whether the value is a known member of the PermissionAnswerRequestDecision enum.
func (e PermissionAnswerRequestDecision) Valid() bool {
	switch e {
	case AllowOnce:
		return true
	case AllowRemember:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// Defines values for FeatureAction.
const (
	FeatureActionCleanup            FeatureAction = "cleanup"
	FeatureActionDelete             FeatureAction = "delete"
	FeatureActionMarkDone           FeatureAction = "mark-done"
	FeatureActionMerge              FeatureAction = "merge"
	FeatureActionNeedUserInput      FeatureAction = "need-user-input"
	FeatureActionNeedUserInputDraft FeatureAction = "need-user-input-draft"
	FeatureActionPauseStop          FeatureAction = "pause-stop"
	FeatureActionPublish            FeatureAction = "publish"
	FeatureActionRebase             FeatureAction = "rebase"
	FeatureActionRefactor           FeatureAction = "refactor"
	FeatureActionRestart            FeatureAction = "restart"
	FeatureActionResume             FeatureAction = "resume"
	FeatureActionRetry              FeatureAction = "retry"
	FeatureActionReviewComments     FeatureAction = "review-comments"
	FeatureActionReviewDecision     FeatureAction = "review-decision"
	FeatureActionRewind             FeatureAction = "rewind"
	FeatureActionStart              FeatureAction = "start"
)

// Valid indicates whether the value is a known member of the FeatureAction enum.
func (e FeatureAction) Valid() bool {
	switch e {
	case FeatureActionCleanup:
		return true
	case FeatureActionDelete:
		return true
	case FeatureActionMarkDone:
		return true
	case FeatureActionMerge:
		return true
	case FeatureActionNeedUserInput:
		return true
	case FeatureActionNeedUserInputDraft:
		return true
	case FeatureActionPauseStop:
		return true
	case FeatureActionPublish:
		return true
	case FeatureActionRebase:
		return true
	case FeatureActionRefactor:
		return true
	case FeatureActionRestart:
		return true
	case FeatureActionResume:
		return true
	case FeatureActionRetry:
		return true
	case FeatureActionReviewComments:
		return true
	case FeatureActionReviewDecision:
		return true
	case FeatureActionRewind:
		return true
	case FeatureActionStart:
		return true
	default:
		return false
	}
}

// Defines values for FeatureSubaction.
const (
	FeatureSubactionDescription FeatureSubaction = "description"
	FeatureSubactionFetch       FeatureSubaction = "fetch"
	FeatureSubactionFinish      FeatureSubaction = "finish"
	FeatureSubactionRestart     FeatureSubaction = "restart"
)

// Valid indicates whether the value is a known member of the FeatureSubaction enum.
func (e FeatureSubaction) Valid() bool {
	switch e {
	case FeatureSubactionDescription:
		return true
	case FeatureSubactionFetch:
		return true
	case FeatureSubactionFinish:
		return true
	case FeatureSubactionRestart:
		return true
	default:
		return false
	}
}

// Defines values for TrustedMutationHeader.
const (
	TrustedMutationHeaderLocal TrustedMutationHeader = "local"
)

// Valid indicates whether the value is a known member of the TrustedMutationHeader enum.
func (e TrustedMutationHeader) Valid() bool {
	switch e {
	case TrustedMutationHeaderLocal:
		return true
	default:
		return false
	}
}

// Defines values for PatchRuntimeConfigParamsXAgenticoClient.
const (
	PatchRuntimeConfigParamsXAgenticoClientLocal PatchRuntimeConfigParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the PatchRuntimeConfigParamsXAgenticoClient enum.
func (e PatchRuntimeConfigParamsXAgenticoClient) Valid() bool {
	switch e {
	case PatchRuntimeConfigParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for PutRuntimeConfigParamsXAgenticoClient.
const (
	PutRuntimeConfigParamsXAgenticoClientLocal PutRuntimeConfigParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the PutRuntimeConfigParamsXAgenticoClient enum.
func (e PutRuntimeConfigParamsXAgenticoClient) Valid() bool {
	switch e {
	case PutRuntimeConfigParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for CreateFeatureParamsXAgenticoClient.
const (
	CreateFeatureParamsXAgenticoClientLocal CreateFeatureParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the CreateFeatureParamsXAgenticoClient enum.
func (e CreateFeatureParamsXAgenticoClient) Valid() bool {
	switch e {
	case CreateFeatureParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureActionParamsXAgenticoClient.
const (
	RunFeatureActionParamsXAgenticoClientLocal RunFeatureActionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the RunFeatureActionParamsXAgenticoClient enum.
func (e RunFeatureActionParamsXAgenticoClient) Valid() bool {
	switch e {
	case RunFeatureActionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureActionParamsAction.
const (
	RunFeatureActionParamsActionCleanup            RunFeatureActionParamsAction = "cleanup"
	RunFeatureActionParamsActionDelete             RunFeatureActionParamsAction = "delete"
	RunFeatureActionParamsActionMarkDone           RunFeatureActionParamsAction = "mark-done"
	RunFeatureActionParamsActionMerge              RunFeatureActionParamsAction = "merge"
	RunFeatureActionParamsActionNeedUserInput      RunFeatureActionParamsAction = "need-user-input"
	RunFeatureActionParamsActionNeedUserInputDraft RunFeatureActionParamsAction = "need-user-input-draft"
	RunFeatureActionParamsActionPauseStop          RunFeatureActionParamsAction = "pause-stop"
	RunFeatureActionParamsActionPublish            RunFeatureActionParamsAction = "publish"
	RunFeatureActionParamsActionRebase             RunFeatureActionParamsAction = "rebase"
	RunFeatureActionParamsActionRefactor           RunFeatureActionParamsAction = "refactor"
	RunFeatureActionParamsActionRestart            RunFeatureActionParamsAction = "restart"
	RunFeatureActionParamsActionResume             RunFeatureActionParamsAction = "resume"
	RunFeatureActionParamsActionRetry              RunFeatureActionParamsAction = "retry"
	RunFeatureActionParamsActionReviewComments     RunFeatureActionParamsAction = "review-comments"
	RunFeatureActionParamsActionReviewDecision     RunFeatureActionParamsAction = "review-decision"
	RunFeatureActionParamsActionRewind             RunFeatureActionParamsAction = "rewind"
	RunFeatureActionParamsActionStart              RunFeatureActionParamsAction = "start"
)

// Valid indicates whether the value is a known member of the RunFeatureActionParamsAction enum.
func (e RunFeatureActionParamsAction) Valid() bool {
	switch e {
	case RunFeatureActionParamsActionCleanup:
		return true
	case RunFeatureActionParamsActionDelete:
		return true
	case RunFeatureActionParamsActionMarkDone:
		return true
	case RunFeatureActionParamsActionMerge:
		return true
	case RunFeatureActionParamsActionNeedUserInput:
		return true
	case RunFeatureActionParamsActionNeedUserInputDraft:
		return true
	case RunFeatureActionParamsActionPauseStop:
		return true
	case RunFeatureActionParamsActionPublish:
		return true
	case RunFeatureActionParamsActionRebase:
		return true
	case RunFeatureActionParamsActionRefactor:
		return true
	case RunFeatureActionParamsActionRestart:
		return true
	case RunFeatureActionParamsActionResume:
		return true
	case RunFeatureActionParamsActionRetry:
		return true
	case RunFeatureActionParamsActionReviewComments:
		return true
	case RunFeatureActionParamsActionReviewDecision:
		return true
	case RunFeatureActionParamsActionRewind:
		return true
	case RunFeatureActionParamsActionStart:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureSubactionParamsXAgenticoClient.
const (
	RunFeatureSubactionParamsXAgenticoClientLocal RunFeatureSubactionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the RunFeatureSubactionParamsXAgenticoClient enum.
func (e RunFeatureSubactionParamsXAgenticoClient) Valid() bool {
	switch e {
	case RunFeatureSubactionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureSubactionParamsAction.
const (
	RunFeatureSubactionParamsActionCleanup            RunFeatureSubactionParamsAction = "cleanup"
	RunFeatureSubactionParamsActionDelete             RunFeatureSubactionParamsAction = "delete"
	RunFeatureSubactionParamsActionMarkDone           RunFeatureSubactionParamsAction = "mark-done"
	RunFeatureSubactionParamsActionMerge              RunFeatureSubactionParamsAction = "merge"
	RunFeatureSubactionParamsActionNeedUserInput      RunFeatureSubactionParamsAction = "need-user-input"
	RunFeatureSubactionParamsActionNeedUserInputDraft RunFeatureSubactionParamsAction = "need-user-input-draft"
	RunFeatureSubactionParamsActionPauseStop          RunFeatureSubactionParamsAction = "pause-stop"
	RunFeatureSubactionParamsActionPublish            RunFeatureSubactionParamsAction = "publish"
	RunFeatureSubactionParamsActionRebase             RunFeatureSubactionParamsAction = "rebase"
	RunFeatureSubactionParamsActionRefactor           RunFeatureSubactionParamsAction = "refactor"
	RunFeatureSubactionParamsActionRestart            RunFeatureSubactionParamsAction = "restart"
	RunFeatureSubactionParamsActionResume             RunFeatureSubactionParamsAction = "resume"
	RunFeatureSubactionParamsActionRetry              RunFeatureSubactionParamsAction = "retry"
	RunFeatureSubactionParamsActionReviewComments     RunFeatureSubactionParamsAction = "review-comments"
	RunFeatureSubactionParamsActionReviewDecision     RunFeatureSubactionParamsAction = "review-decision"
	RunFeatureSubactionParamsActionRewind             RunFeatureSubactionParamsAction = "rewind"
	RunFeatureSubactionParamsActionStart              RunFeatureSubactionParamsAction = "start"
)

// Valid indicates whether the value is a known member of the RunFeatureSubactionParamsAction enum.
func (e RunFeatureSubactionParamsAction) Valid() bool {
	switch e {
	case RunFeatureSubactionParamsActionCleanup:
		return true
	case RunFeatureSubactionParamsActionDelete:
		return true
	case RunFeatureSubactionParamsActionMarkDone:
		return true
	case RunFeatureSubactionParamsActionMerge:
		return true
	case RunFeatureSubactionParamsActionNeedUserInput:
		return true
	case RunFeatureSubactionParamsActionNeedUserInputDraft:
		return true
	case RunFeatureSubactionParamsActionPauseStop:
		return true
	case RunFeatureSubactionParamsActionPublish:
		return true
	case RunFeatureSubactionParamsActionRebase:
		return true
	case RunFeatureSubactionParamsActionRefactor:
		return true
	case RunFeatureSubactionParamsActionRestart:
		return true
	case RunFeatureSubactionParamsActionResume:
		return true
	case RunFeatureSubactionParamsActionRetry:
		return true
	case RunFeatureSubactionParamsActionReviewComments:
		return true
	case RunFeatureSubactionParamsActionReviewDecision:
		return true
	case RunFeatureSubactionParamsActionRewind:
		return true
	case RunFeatureSubactionParamsActionStart:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureSubactionParamsSubaction.
const (
	Description RunFeatureSubactionParamsSubaction = "description"
	Fetch       RunFeatureSubactionParamsSubaction = "fetch"
	Finish      RunFeatureSubactionParamsSubaction = "finish"
	Restart     RunFeatureSubactionParamsSubaction = "restart"
)

// Valid indicates whether the value is a known member of the RunFeatureSubactionParamsSubaction enum.
func (e RunFeatureSubactionParamsSubaction) Valid() bool {
	switch e {
	case Description:
		return true
	case Fetch:
		return true
	case Finish:
		return true
	case Restart:
		return true
	default:
		return false
	}
}

// Defines values for UpdateFeatureConfigParamsXAgenticoClient.
const (
	UpdateFeatureConfigParamsXAgenticoClientLocal UpdateFeatureConfigParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the UpdateFeatureConfigParamsXAgenticoClient enum.
func (e UpdateFeatureConfigParamsXAgenticoClient) Valid() bool {
	switch e {
	case UpdateFeatureConfigParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for CreateReviewSessionParamsXAgenticoClient.
const (
	CreateReviewSessionParamsXAgenticoClientLocal CreateReviewSessionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the CreateReviewSessionParamsXAgenticoClient enum.
func (e CreateReviewSessionParamsXAgenticoClient) Valid() bool {
	switch e {
	case CreateReviewSessionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for SubmitReviewSessionDecisionParamsXAgenticoClient.
const (
	SubmitReviewSessionDecisionParamsXAgenticoClientLocal SubmitReviewSessionDecisionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the SubmitReviewSessionDecisionParamsXAgenticoClient enum.
func (e SubmitReviewSessionDecisionParamsXAgenticoClient) Valid() bool {
	switch e {
	case SubmitReviewSessionDecisionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for SaveReviewDraftParamsXAgenticoClient.
const (
	SaveReviewDraftParamsXAgenticoClientLocal SaveReviewDraftParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the SaveReviewDraftParamsXAgenticoClient enum.
func (e SaveReviewDraftParamsXAgenticoClient) Valid() bool {
	switch e {
	case SaveReviewDraftParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for AnswerPermissionParamsXAgenticoClient.
const (
	AnswerPermissionParamsXAgenticoClientLocal AnswerPermissionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the AnswerPermissionParamsXAgenticoClient enum.
func (e AnswerPermissionParamsXAgenticoClient) Valid() bool {
	switch e {
	case AnswerPermissionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for AnswerAskUserPromptParamsXAgenticoClient.
const (
	AnswerAskUserPromptParamsXAgenticoClientLocal AnswerAskUserPromptParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the AnswerAskUserPromptParamsXAgenticoClient enum.
func (e AnswerAskUserPromptParamsXAgenticoClient) Valid() bool {
	switch e {
	case AnswerAskUserPromptParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for StartChatPromptParamsXAgenticoClient.
const (
	StartChatPromptParamsXAgenticoClientLocal StartChatPromptParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the StartChatPromptParamsXAgenticoClient enum.
func (e StartChatPromptParamsXAgenticoClient) Valid() bool {
	switch e {
	case StartChatPromptParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for SendHelpPromptParamsXAgenticoClient.
const (
	SendHelpPromptParamsXAgenticoClientLocal SendHelpPromptParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the SendHelpPromptParamsXAgenticoClient enum.
func (e SendHelpPromptParamsXAgenticoClient) Valid() bool {
	switch e {
	case SendHelpPromptParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for ExecuteRecoveryActionsParamsXAgenticoClient.
const (
	ExecuteRecoveryActionsParamsXAgenticoClientLocal ExecuteRecoveryActionsParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the ExecuteRecoveryActionsParamsXAgenticoClient enum.
func (e ExecuteRecoveryActionsParamsXAgenticoClient) Valid() bool {
	switch e {
	case ExecuteRecoveryActionsParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for ShutdownRuntimeParamsXAgenticoClient.
const (
	ShutdownRuntimeParamsXAgenticoClientLocal ShutdownRuntimeParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the ShutdownRuntimeParamsXAgenticoClient enum.
func (e ShutdownRuntimeParamsXAgenticoClient) Valid() bool {
	switch e {
	case ShutdownRuntimeParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Action defines model for Action.
type Action struct {
	DisabledReasons []ActionDisabledReason `json:"disabled_reasons,omitempty"`
	Enabled         bool                   `json:"enabled"`
	ID              string                 `json:"id"`
	RequiredInputs  []ActionInput          `json:"required_inputs"`
	Scope           ActionScope            `json:"scope"`
}

// ActionBaseResponse defines model for ActionBaseResponse.
type ActionBaseResponse = JSONResponse

// ActionDisabledReason defines model for ActionDisabledReason.
type ActionDisabledReason struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ActionInput defines model for ActionInput.
type ActionInput struct {
	Kind      string   `json:"kind"`
	MaxLength int      `json:"max_length,omitempty"`
	Name      string   `json:"name"`
	Options   []string `json:"options,omitempty"`
	Required  bool     `json:"required"`
}

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	APIVersion                    string                        `json:"api_version"`
	AskUserAnswerResponse         AskUserAnswerResponse         `json:"ask_user_answer_response,omitempty"`
	ChatStartResponse             ChatStartResponse             `json:"chat_start_response,omitempty"`
	CleanupFeatureResponse        CleanupFeatureResponse        `json:"cleanup_feature_response,omitempty"`
	CreateFeatureResponse         CreateFeatureResponse         `json:"create_feature_response,omitempty"`
	DeleteFeatureResponse         DeleteFeatureResponse         `json:"delete_feature_response,omitempty"`
	FeatureConfigUpdateResponse   FeatureConfigUpdateResponse   `json:"feature_config_update_response,omitempty"`
	FeatureRestartResponse        FeatureRestartResponse        `json:"feature_restart_response,omitempty"`
	FeatureStartResponse          FeatureStartResponse          `json:"feature_start_response,omitempty"`
	FeatureStopResponse           FeatureStopResponse           `json:"feature_stop_response,omitempty"`
	HelpSendResponse              HelpSendResponse              `json:"help_send_response,omitempty"`
	MarkDoneResponse              MarkDoneResponse              `json:"mark_done_response,omitempty"`
	MergeFeatureResponse          MergeFeatureResponse          `json:"merge_feature_response,omitempty"`
	Meta                          ResponseMeta                  `json:"meta,omitempty"`
	NeedUserInputDecisionResponse NeedUserInputDecisionResponse `json:"need_user_input_decision_response,omitempty"`
	NeedUserInputDraftResponse    NeedUserInputDraftResponse    `json:"need_user_input_draft_response,omitempty"`
	PermissionAnswerResponse      PermissionAnswerResponse      `json:"permission_answer_response,omitempty"`
	PublishDescriptionResponse    PublishDescriptionResponse    `json:"publish_description_response,omitempty"`
	PublishFeatureResponse        PublishFeatureResponse        `json:"publish_feature_response,omitempty"`
	RebaseStartResponse           RebaseStartResponse           `json:"rebase_start_response,omitempty"`
	RecoveryActionResponse        RecoveryActionResponse        `json:"recovery_action_response,omitempty"`
	RefactorRestartResponse       RefactorRestartResponse       `json:"refactor_restart_response,omitempty"`
	RefactorStartResponse         RefactorStartResponse         `json:"refactor_start_response,omitempty"`
	RetryFeatureResponse          RetryFeatureResponse          `json:"retry_feature_response,omitempty"`
	ReviewCommentsFetchResponse   ReviewCommentsFetchResponse   `json:"review_comments_fetch_response,omitempty"`
	ReviewCommentsStartResponse   ReviewCommentsStartResponse   `json:"review_comments_start_response,omitempty"`
	ReviewDecisionResponse        ReviewDecisionResponse        `json:"review_decision_response,omitempty"`
	RewindFeatureResponse         RewindFeatureResponse         `json:"rewind_feature_response,omitempty"`
	RuntimeConfigUpdateResponse   RuntimeConfigUpdateResponse   `json:"runtime_config_update_response,omitempty"`
	ShutdownResponse              ShutdownResponse              `json:"shutdown_response,omitempty"`
}

// ActionResult defines model for ActionResult.
type ActionResult struct {
	Result string `json:"result"`
}

// ActionScope defines model for ActionScope.
type ActionScope struct {
	CycleType     string `json:"cycle_type,omitempty"`
	RepoSelection string `json:"repo_selection,omitempty"`
	Type          string `json:"type"`
}

// Artifact defines model for Artifact.
type Artifact struct {
	Category         string    `json:"category"`
	ContentAvailable bool      `json:"content_available"`
	ID               string    `json:"id"`
	Iteration        int       `json:"iteration,omitempty"`
	ModifiedAt       time.Time `json:"modified_at,omitempty"`
	Path             string    `json:"path,omitempty"`
	Phase            string    `json:"phase,omitempty"`
	RunNumber        int       `json:"run_number"`
	Size             int64     `json:"size,omitempty"`
	Type             string    `json:"type"`
}

// ArtifactListResponse defines model for ArtifactListResponse.
type ArtifactListResponse struct {
	APIVersion string       `json:"api_version"`
	Artifacts  []Artifact   `json:"artifacts"`
	Meta       ResponseMeta `json:"meta,omitempty"`
}

// AskUserAnswerResponse defines model for AskUserAnswerResponse.
type AskUserAnswerResponse struct {
	APIVersion string       `json:"api_version"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	RequestID  string       `json:"request_id"`
	Result     string       `json:"result"`
	SessionID  string       `json:"session_id"`
}

// AskUserOption defines model for AskUserOption.
type AskUserOption struct {
	Confidence  *float64 `json:"confidence,omitempty"`
	Description string   `json:"description,omitempty"`
	Label       string   `json:"label,omitempty"`
}

// AskUserQuestion defines model for AskUserQuestion.
type AskUserQuestion struct {
	Header      string          `json:"header,omitempty"`
	MultiSelect bool            `json:"multi_select,omitempty"`
	Options     []AskUserOption `json:"options,omitempty"`
	Question    string          `json:"question,omitempty"`
}

// AutomaticReviewState defines model for AutomaticReviewState.
type AutomaticReviewState struct {
	Enabled bool                       `json:"enabled"`
	Mode    AutomaticReviewStateMode   `json:"mode"`
	Source  AutomaticReviewStateSource `json:"source"`
}

// AutomaticReviewStateMode defines model for AutomaticReviewState.Mode.
type AutomaticReviewStateMode string

// AutomaticReviewStateSource defines model for AutomaticReviewState.Source.
type AutomaticReviewStateSource string

// ChatStartResponse defines model for ChatStartResponse.
type ChatStartResponse struct {
	APIVersion string       `json:"api_version"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
	SessionID  string       `json:"session_id"`
}

// Checkpoints defines model for Checkpoints.
type Checkpoints struct {
	DesignReview    bool `json:"design_review"`
	DraftPublish    bool `json:"draft_publish"`
	InquiryReview   bool `json:"inquiry_review"`
	ManualPublish   bool `json:"manual_publish"`
	PhasePlanReview bool `json:"phase_plan_review"`
	ResearchReview  bool `json:"research_review"`
	RoadmapReview   bool `json:"roadmap_review"`
}

// CleanupFeatureResponse defines model for CleanupFeatureResponse.
type CleanupFeatureResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
	Target     string       `json:"target,omitempty"`
}

// ConfigRepo defines model for ConfigRepo.
type ConfigRepo struct {
	Name          string                        `json:"name"`
	Path          string                        `json:"path,omitempty"`
	PipelineGates map[string]config.Checkpoints `json:"pipeline_gates,omitempty"`
}

// Context defines model for Context.
type Context struct {
	Percentage int `json:"percentage"`
}

// ControlRequest defines model for ControlRequest.
type ControlRequest struct {
	FeatureID string                     `json:"feature_id,omitempty"`
	Input     map[string]interface{}     `json:"input,omitempty"`
	Phase     string                     `json:"phase,omitempty"`
	Questions []AskUserQuestion          `json:"questions,omitempty"`
	Remember  *PermissionRememberPreview `json:"remember,omitempty"`
	RequestID string                     `json:"request_id"`
	SessionID string                     `json:"session_id,omitempty"`
	Status    string                     `json:"status"`
	Summary   string                     `json:"summary,omitempty"`
	ToolName  string                     `json:"tool_name"`
}

// Cost defines model for Cost.
type Cost struct {
	ByPhase  map[string]float64 `json:"by_phase"`
	TotalUSD float64            `json:"total_usd"`
}

// CreateFeatureResponse defines model for CreateFeatureResponse.
type CreateFeatureResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// Cursor defines model for Cursor.
type Cursor struct {
	End   int `json:"end"`
	Start int `json:"start"`
	Total int `json:"total"`
}

// Cycle defines model for Cycle.
type Cycle struct {
	Count     int    `json:"count,omitempty"`
	Iteration int    `json:"iteration,omitempty"`
	Status    string `json:"status,omitempty"`
	Type      string `json:"type,omitempty"`
}

// DeleteFeatureResponse defines model for DeleteFeatureResponse.
type DeleteFeatureResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// EffortConfig defines model for EffortConfig.
type EffortConfig = config.EffortConfig

// Error defines model for Error.
type Error struct {
	Code    string                 `json:"code"`
	Message string                 `json:"message"`
	Status  int                    `json:"status"`
	Target  map[string]interface{} `json:"target,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	APIVersion string `json:"api_version"`
	Error      Error  `json:"error"`
}

// Failure defines model for Failure.
type Failure struct {
	Message string `json:"message,omitempty"`
	Type    string `json:"type,omitempty"`
}

// FeatureActionResult defines model for FeatureActionResult.
type FeatureActionResult struct {
	FeatureID string `json:"feature_id"`
	Result    string `json:"result"`
}

// FeatureConfig defines model for FeatureConfig.
type FeatureConfig struct {
	AutomaticReviewMode FeatureConfigAutomaticReviewMode `json:"automatic_review_mode,omitempty"`
	Checkpoints         Checkpoints                      `json:"checkpoints"`
	Effort              EffortConfig                     `json:"effort,omitempty"`
	InputNotifications  FeatureConfigInputNotifications  `json:"input_notifications,omitempty"`
	Inquireness         string                           `json:"inquireness"`
	Models              ModelDefaults                    `json:"models"`
	Pipeline            string                           `json:"pipeline,omitempty"`
}

// FeatureConfigAutomaticReviewMode defines model for FeatureConfig.AutomaticReviewMode.
type FeatureConfigAutomaticReviewMode string

// FeatureConfigInputNotifications defines model for FeatureConfig.InputNotifications.
type FeatureConfigInputNotifications string

// FeatureConfigResponse defines model for FeatureConfigResponse.
type FeatureConfigResponse struct {
	APIVersion string         `json:"api_version"`
	Current    FeatureConfig  `json:"current"`
	Defaults   FeatureConfig  `json:"defaults"`
	FeatureID  string         `json:"feature_id"`
	Meta       ResponseMeta   `json:"meta,omitempty"`
	Original   FeatureConfig  `json:"original"`
	Publish    Publishability `json:"publishability"`
}

// FeatureConfigUpdateResponse defines model for FeatureConfigUpdateResponse.
type FeatureConfigUpdateResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// FeatureDefaults defines model for FeatureDefaults.
type FeatureDefaults struct {
	AutomaticReviewEnabled bool                                 `json:"automatic_review_enabled,omitempty"`
	Checkpoints            config.Checkpoints                   `json:"checkpoints"`
	Effort                 EffortConfig                         `json:"effort,omitempty"`
	Inquireness            string                               `json:"inquireness,omitempty"`
	Models                 ModelDefaults                        `json:"models"`
	Pipeline               string                               `json:"pipeline,omitempty"`
	PipelinePreferences    map[string]config.PipelinePreference `json:"pipeline_preferences,omitempty"`
}

// FeatureDetail defines model for FeatureDetail.
type FeatureDetail struct {
	Actions         []Action             `json:"actions"`
	ActiveRun       int                  `json:"active_run"`
	ActiveRunDetail *RunSummary          `json:"active_run_detail,omitempty"`
	AutomaticReview AutomaticReviewState `json:"automatic_review"`
	CacheRevalidate string               `json:"cache_revalidate"`
	Checkpoints     Checkpoints          `json:"checkpoints"`
	Cost            Cost                 `json:"cost"`
	CreatedAt       time.Time            `json:"created_at"`
	CurrentPhase    string               `json:"current_phase"`
	Cycle           *Cycle               `json:"cycle,omitempty"`
	Description     string               `json:"description,omitempty"`
	Failure         *Failure             `json:"failure,omitempty"`
	HistoricalRuns  []RunSummary         `json:"historical_runs"`
	ID              string               `json:"id"`
	Models          ModelDefaults        `json:"models"`
	Name            string               `json:"name"`
	NeedUserInput   *NeedUserInputGate   `json:"need_user_input,omitempty"`
	Pipeline        string               `json:"pipeline,omitempty"`
	Progress        FeatureProgress      `json:"progress"`
	RepoStatus      []RepoStatus         `json:"repo_status"`
	Repos           []string             `json:"repos"`

	// ResumeCount Number of persisted provider-session resumptions for the active phase unit.
	ResumeCount int `json:"resume_count"`

	// Resumed Whether the active phase unit has resumed a persisted provider session.
	Resumed           bool               `json:"resumed"`
	ReviewGate        ReviewGate         `json:"review_gate"`
	Revision          string             `json:"revision"`
	RunCount          int                `json:"run_count"`
	Slug              string             `json:"slug"`
	Status            string             `json:"status"`
	Summary           string             `json:"summary,omitempty"`
	Timing            Timing             `json:"timing"`
	VerificationItems []VerificationItem `json:"verification_items,omitempty"`
	Warnings          []Warning          `json:"warnings,omitempty"`
}

// FeatureDetailResponse defines model for FeatureDetailResponse.
type FeatureDetailResponse struct {
	APIVersion string        `json:"api_version"`
	Feature    FeatureDetail `json:"feature"`
	Meta       ResponseMeta  `json:"meta,omitempty"`
}

// FeatureListResponse defines model for FeatureListResponse.
type FeatureListResponse struct {
	APIVersion string           `json:"api_version"`
	Features   []FeatureSummary `json:"features"`
	Meta       ResponseMeta     `json:"meta,omitempty"`
	Warnings   []Warning        `json:"warnings,omitempty"`
}

// FeatureProgress defines model for FeatureProgress.
type FeatureProgress struct {
	CurrentIteration    int    `json:"current_iteration,omitempty"`
	CurrentPhaseStatus  string `json:"current_phase_status,omitempty"`
	CurrentRoadmapPhase int    `json:"current_roadmap_phase,omitempty"`
	TotalRoadmapPhases  int    `json:"total_roadmap_phases,omitempty"`
}

// FeatureRestartResponse defines model for FeatureRestartResponse.
type FeatureRestartResponse struct {
	APIVersion     string       `json:"api_version"`
	Dispatch       string       `json:"dispatch,omitempty"`
	FeatureID      string       `json:"feature_id"`
	Meta           ResponseMeta `json:"meta,omitempty"`
	Phase          string       `json:"phase,omitempty"`
	RefactorCount  int          `json:"refactor_count,omitempty"`
	RepoCycleCount int          `json:"repo_cycle_count,omitempty"`
	Result         string       `json:"result"`
	SessionIDs     []string     `json:"session_ids,omitempty"`
}

// FeatureStartResponse defines model for FeatureStartResponse.
type FeatureStartResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Phase      string       `json:"phase,omitempty"`
	Result     string       `json:"result"`
	SessionIDs []string     `json:"session_ids,omitempty"`
}

// FeatureStopResponse defines model for FeatureStopResponse.
type FeatureStopResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// FeatureSummary defines model for FeatureSummary.
type FeatureSummary struct {
	ActiveRun    int             `json:"active_run"`
	Checkpoints  Checkpoints     `json:"checkpoints"`
	CreatedAt    time.Time       `json:"created_at"`
	CurrentPhase string          `json:"current_phase"`
	Cycle        *Cycle          `json:"cycle,omitempty"`
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Progress     FeatureProgress `json:"progress"`
	Repos        []string        `json:"repos"`

	// ResumeCount Number of persisted provider-session resumptions for the active phase unit.
	ResumeCount int `json:"resume_count"`

	// Resumed Whether the active phase unit has resumed a persisted provider session.
	Resumed  bool      `json:"resumed"`
	RunCount int       `json:"run_count"`
	Slug     string    `json:"slug"`
	Status   string    `json:"status"`
	Warnings []Warning `json:"warnings,omitempty"`
}

// FileChange defines model for FileChange.
type FileChange struct {
	AddedLines   int    `json:"added_lines,omitempty"`
	Detail       string `json:"detail,omitempty"`
	HasDiffPatch bool   `json:"has_diff_patch,omitempty"`
	OldPath      string `json:"old_path,omitempty"`
	Operation    string `json:"operation,omitempty"`
	Path         string `json:"path,omitempty"`
	RemovedLines int    `json:"removed_lines,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	APIVersion   string          `json:"api_version"`
	LaunchPolicy LaunchPolicy    `json:"launch_policy"`
	Meta         ResponseMeta    `json:"meta,omitempty"`
	Owner        Owner           `json:"owner"`
	Runtime      RuntimeIdentity `json:"runtime"`
	ServerTime   time.Time       `json:"server_time"`
	StartedAt    time.Time       `json:"started_at"`
	Status       string          `json:"status"`
}

// HelpQueue defines model for HelpQueue.
type HelpQueue struct {
	FeatureID string    `json:"feature_id"`
	Pending   bool      `json:"pending"`
	Question  string    `json:"question"`
	Time      time.Time `json:"time,omitempty"`
}

// HelpSendResponse defines model for HelpSendResponse.
type HelpSendResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
	SessionID  string       `json:"session_id"`
}

// JSONResponse defines model for JSONResponse.
type JSONResponse struct {
	APIVersion string       `json:"api_version"`
	Meta       ResponseMeta `json:"meta,omitempty"`
}

// LaunchPolicy defines model for LaunchPolicy.
type LaunchPolicy struct {
	DangerouslySkipPermissions bool     `json:"dangerously_skip_permissions"`
	Providers                  []string `json:"providers"`
	Resolved                   bool     `json:"resolved"`
}

// LivePreviewResponse defines model for LivePreviewResponse.
type LivePreviewResponse struct {
	Activity   string              `json:"activity"`
	APIVersion string              `json:"api_version"`
	Attention  []ControlRequest    `json:"attention,omitempty"`
	Context    Context             `json:"context"`
	Cost       Cost                `json:"cost"`
	Feature    FeatureSummary      `json:"feature"`
	Meta       ResponseMeta        `json:"meta,omitempty"`
	Session    *SessionSummary     `json:"session,omitempty"`
	Timing     Timing              `json:"timing"`
	Transcript []TranscriptMessage `json:"transcript"`
}

// MarkDoneResponse defines model for MarkDoneResponse.
type MarkDoneResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// MergeFeatureResponse defines model for MergeFeatureResponse.
type MergeFeatureResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// Model defines model for Model.
type Model struct {
	Aliases            []string `json:"aliases,omitempty"`
	Category           string   `json:"category,omitempty"`
	ContextWindow      int      `json:"context_window,omitempty"`
	DisplayName        string   `json:"display_name,omitempty"`
	EffortCapabilities []string `json:"effort_capabilities,omitempty"`
	ID                 string   `json:"id"`
}

// ModelCatalogResponse defines model for ModelCatalogResponse.
type ModelCatalogResponse struct {
	APIVersion          string                         `json:"api_version"`
	Meta                ResponseMeta                   `json:"meta,omitempty"`
	PhaseDefaults       ModelDefaults                  `json:"phase_defaults"`
	PhaseProviderModels map[string]map[string][]string `json:"phase_provider_models"`
	ProviderModels      map[string][]Model             `json:"provider_models"`
	ProviderOrder       []string                       `json:"provider_order"`
}

// ModelDefaults defines model for ModelDefaults.
type ModelDefaults = config.ModelConfig

// NeedUserInputDecisionResponse defines model for NeedUserInputDecisionResponse.
type NeedUserInputDecisionResponse struct {
	APIVersion string       `json:"api_version"`
	Decision   string       `json:"decision"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// NeedUserInputDraftResponse defines model for NeedUserInputDraftResponse.
type NeedUserInputDraftResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// NeedUserInputGate defines model for NeedUserInputGate.
type NeedUserInputGate struct {
	CycleType          string                  `json:"cycle_type,omitempty"`
	FeatureID          string                  `json:"feature_id,omitempty"`
	InputNotifications string                  `json:"input_notifications,omitempty"`
	Iteration          int                     `json:"iteration,omitempty"`
	Open               bool                    `json:"open"`
	Questions          []NeedUserInputQuestion `json:"questions,omitempty"`
	RepoName           string                  `json:"repo_name,omitempty"`
	Scope              string                  `json:"scope,omitempty"`
	Summary            string                  `json:"summary,omitempty"`
}

// NeedUserInputQuestion defines model for NeedUserInputQuestion.
type NeedUserInputQuestion struct {
	Answer string `json:"answer,omitempty"`
	Index  int    `json:"index,omitempty"`
	Prompt string `json:"prompt,omitempty"`
}

// NotificationConfig defines model for NotificationConfig.
type NotificationConfig struct {
	MuteFeatureInput bool `json:"mute_feature_input"`
}

// Observability defines model for Observability.
type Observability struct {
	Events          bool   `json:"events"`
	OTelEnabled     bool   `json:"otel_enabled"`
	OTelServiceName string `json:"otel_service_name,omitempty"`
}

// Owner defines model for Owner.
type Owner struct {
	PGID      int       `json:"pgid,omitempty"`
	PID       int       `json:"pid"`
	StartedAt time.Time `json:"started_at"`
	Version   string    `json:"version,omitempty"`
}

// PermissionAnswerSchema defines model for PermissionAnswerRequest.
type PermissionAnswerSchema struct {
	Decision        PermissionAnswerRequestDecision `json:"decision"`
	RememberPattern string                          `json:"remember_pattern,omitempty"`

	// RememberScope Existing permission cache scope. Empty string means global.
	RememberScope *string `json:"remember_scope,omitempty"`
	RequestID     string  `json:"request_id"`
	SessionID     string  `json:"session_id,omitempty"`
}

// PermissionAnswerRequestDecision defines model for PermissionAnswerRequest.Decision.
type PermissionAnswerRequestDecision string

// PermissionAnswerResponse defines model for PermissionAnswerResponse.
type PermissionAnswerResponse struct {
	AlreadyExisted bool         `json:"already_existed,omitempty"`
	APIVersion     string       `json:"api_version"`
	AuditWarning   string       `json:"audit_warning,omitempty"`
	Decision       string       `json:"decision"`
	Meta           ResponseMeta `json:"meta,omitempty"`
	RequestID      string       `json:"request_id"`
	Result         string       `json:"result"`
	SessionID      string       `json:"session_id"`
}

// PermissionRememberPreview defines model for PermissionRememberPreview.
type PermissionRememberPreview struct {
	Pattern string `json:"pattern"`

	// Scope Existing permission cache scope. Empty string means global.
	Scope        string `json:"scope"`
	ScopeDisplay string `json:"scope_display"`
}

// PermissionSnapshotResponse defines model for PermissionSnapshotResponse.
type PermissionSnapshotResponse struct {
	APIVersion string           `json:"api_version"`
	Meta       ResponseMeta     `json:"meta,omitempty"`
	Requests   []ControlRequest `json:"requests"`
}

// PromptSnapshotResponse defines model for PromptSnapshotResponse.
type PromptSnapshotResponse struct {
	APIVersion       string              `json:"api_version"`
	AskUserQuestions []ControlRequest    `json:"ask_user_questions"`
	HelpQueue        []HelpQueue         `json:"help_queue"`
	Meta             ResponseMeta        `json:"meta,omitempty"`
	NeedUserInputs   []NeedUserInputGate `json:"need_user_inputs"`
}

// PublishDescriptionResponse defines model for PublishDescriptionResponse.
type PublishDescriptionResponse struct {
	APIVersion string       `json:"api_version"`
	Body       string       `json:"body"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
	Title      string       `json:"title"`
}

// PublishFeatureResponse defines model for PublishFeatureResponse.
type PublishFeatureResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// Publishability defines model for Publishability.
type Publishability struct {
	ManualPublish bool            `json:"manual_publish"`
	Repos         map[string]bool `json:"repos"`
}

// RebaseStartResponse defines model for RebaseStartResponse.
type RebaseStartResponse struct {
	APIVersion string       `json:"api_version"`
	CycleType  string       `json:"cycle_type"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
	SessionID  string       `json:"session_id,omitempty"`
}

// RecoveryActionResponse defines model for RecoveryActionResponse.
type RecoveryActionResponse struct {
	APIVersion string       `json:"api_version"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// RecoveryItem defines model for RecoveryItem.
type RecoveryItem struct {
	AllowedActions []string `json:"allowed_actions"`
	DefaultAction  string   `json:"default_action"`
	FeatureID      string   `json:"feature_id"`
	FeatureName    string   `json:"feature_name,omitempty"`
	Iteration      int      `json:"iteration,omitempty"`
	Key            string   `json:"key"`
	Phase          string   `json:"phase,omitempty"`
	PID            int      `json:"pid,omitempty"`
	ProcessAlive   bool     `json:"process_alive"`
	RepoName       string   `json:"repo_name,omitempty"`
}

// RecoverySnapshotResponse defines model for RecoverySnapshotResponse.
type RecoverySnapshotResponse struct {
	APIVersion string         `json:"api_version"`
	Items      []RecoveryItem `json:"items"`
	Meta       ResponseMeta   `json:"meta,omitempty"`
	SnapshotID string         `json:"snapshot_id"`
}

// RefactorRestartResponse defines model for RefactorRestartResponse.
type RefactorRestartResponse = RefactorStartResponse

// RefactorStartResponse defines model for RefactorStartResponse.
type RefactorStartResponse struct {
	APIVersion string       `json:"api_version"`
	CycleType  string       `json:"cycle_type"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Pipeline   string       `json:"pipeline,omitempty"`
	Repo       string       `json:"repo,omitempty"`
	Result     string       `json:"result"`
	SessionID  string       `json:"session_id,omitempty"`
}

// RepoStatus defines model for RepoStatus.
type RepoStatus struct {
	ConflictFiles []string `json:"conflict_files,omitempty"`
	CycleStatus   string   `json:"cycle_status,omitempty"`
	CycleType     string   `json:"cycle_type,omitempty"`
	Freshness     string   `json:"freshness,omitempty"`
	LastError     string   `json:"last_error,omitempty"`
	Name          string   `json:"name"`
	PRURL         string   `json:"pr_url,omitempty"`
	Publishable   bool     `json:"publishable"`
	RebaseStatus  string   `json:"rebase_status,omitempty"`
	RebaseTarget  string   `json:"rebase_target,omitempty"`
	Touched       bool     `json:"touched"`
}

// Resource defines model for Resource.
type Resource struct {
	FeatureID string `json:"feature_id,omitempty"`
	ID        string `json:"id,omitempty"`
	Phase     string `json:"phase,omitempty"`
	Type      string `json:"type"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	AsOfSeq     uint64    `json:"as_of_seq"`
	GeneratedAt time.Time `json:"generated_at"`
	Revision    string    `json:"revision"`
}

// RetryFeatureResponse defines model for RetryFeatureResponse.
type RetryFeatureResponse struct {
	APIVersion string       `json:"api_version"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// ReviewComment defines model for ReviewComment.
type ReviewComment struct {
	Body      string `json:"body,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	DiffHunk  string `json:"diff_hunk,omitempty"`
	ID        int    `json:"id"`
	InReplyTo int    `json:"in_reply_to_id,omitempty"`
	Line      int    `json:"line,omitempty"`
	Path      string `json:"path,omitempty"`
	RepoName  string `json:"repo_name,omitempty"`
	Type      string `json:"type,omitempty"`
	UserLogin string `json:"user_login,omitempty"`
}

// ReviewCommentsFetchResponse defines model for ReviewCommentsFetchResponse.
type ReviewCommentsFetchResponse struct {
	APIVersion string          `json:"api_version"`
	Comments   []ReviewComment `json:"comments"`
	FeatureID  string          `json:"feature_id"`
	Meta       ResponseMeta    `json:"meta,omitempty"`
	Mode       string          `json:"mode,omitempty"`
	Repo       string          `json:"repo"`
}

// ReviewCommentsStartResponse defines model for ReviewCommentsStartResponse.
type ReviewCommentsStartResponse struct {
	APIVersion   string       `json:"api_version"`
	CommentCount int          `json:"comment_count,omitempty"`
	CycleType    string       `json:"cycle_type"`
	FeatureID    string       `json:"feature_id"`
	Meta         ResponseMeta `json:"meta,omitempty"`
	Mode         string       `json:"mode"`
	Repo         string       `json:"repo"`
	Result       string       `json:"result"`
	SessionID    string       `json:"session_id,omitempty"`
	Source       string       `json:"source,omitempty"`
}

// ReviewDecisionResponse defines model for ReviewDecisionResponse.
type ReviewDecisionResponse struct {
	APIVersion string       `json:"api_version"`
	Decision   string       `json:"decision"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// ReviewDraftUpdateRequest defines model for ReviewDraftUpdateRequest.
type ReviewDraftUpdateRequest struct {
	BaseRevision string `json:"base_revision"`
	Text         string `json:"text"`
}

// ReviewGate defines model for ReviewGate.
type ReviewGate struct {
	ReviewFixing      bool              `json:"review_fixing"`
	ReviewingGate     bool              `json:"reviewing_gate"`
	ValidatingPlan    bool              `json:"validating_plan"`
	ValidatorStatuses map[string]string `json:"validator_statuses,omitempty"`
}

// ReviewSessionDecisionRequest defines model for ReviewSessionDecisionRequest.
type ReviewSessionDecisionRequest struct {
	BaseRevision string `json:"base_revision"`
	Decision     string `json:"decision"`
}

// ReviewSessionDecisionResponse defines model for ReviewSessionDecisionResponse.
type ReviewSessionDecisionResponse struct {
	APIVersion string       `json:"api_version"`
	Decision   string       `json:"decision,omitempty"`
	FeatureID  string       `json:"feature_id"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
	ReviewID   string       `json:"review_id"`
}

// ReviewSessionResponse defines model for ReviewSessionResponse.
type ReviewSessionResponse struct {
	APIVersion     string       `json:"api_version"`
	ArtifactID     string       `json:"artifact_id"`
	CanIterate     bool         `json:"can_iterate"`
	DraftRevision  string       `json:"draft_revision"`
	FeatureID      string       `json:"feature_id"`
	Meta           ResponseMeta `json:"meta,omitempty"`
	ReviewID       string       `json:"review_id"`
	ReviewMode     string       `json:"review_mode"`
	RunNumber      int          `json:"run_number"`
	SourceRevision string       `json:"source_revision"`
	TargetPhase    string       `json:"target_phase"`
	Text           string       `json:"text"`
}

// RewindFeatureResponse defines model for RewindFeatureResponse.
type RewindFeatureResponse struct {
	APIVersion      string       `json:"api_version"`
	EffectivePhase  string       `json:"effective_phase,omitempty"`
	FeatureID       string       `json:"feature_id"`
	Meta            ResponseMeta `json:"meta,omitempty"`
	Result          string       `json:"result"`
	RoadmapPhase    int          `json:"roadmap_phase,omitempty"`
	TargetPhase     string       `json:"target_phase,omitempty"`
	UpgradePipeline string       `json:"upgrade_pipeline,omitempty"`
	WarningCount    int          `json:"warning_count,omitempty"`
}

// RunSummary defines model for RunSummary.
type RunSummary struct {
	ArtifactCount                   int        `json:"artifact_count"`
	CurrentPhase                    string     `json:"current_phase,omitempty"`
	HasNeedUserGate                 bool       `json:"has_need_user_gate,omitempty"`
	IsRewind                        bool       `json:"is_rewind,omitempty"`
	Iteration                       int        `json:"iteration,omitempty"`
	PendingReviewPhase              string     `json:"pending_review_phase,omitempty"`
	PendingRewindReviewRoadmapPhase int        `json:"pending_rewind_review_roadmap_phase,omitempty"`
	PhaseStatus                     string     `json:"phase_status,omitempty"`
	RoadmapPhase                    int        `json:"roadmap_phase,omitempty"`
	RoadmapTotal                    int        `json:"roadmap_total,omitempty"`
	RunNumber                       int        `json:"run_number"`
	SealReason                      string     `json:"seal_reason,omitempty"`
	SealedAt                        *time.Time `json:"sealed_at,omitempty"`
	Setup                           *Setup     `json:"setup,omitempty"`
	StartedAt                       *time.Time `json:"started_at,omitempty"`
}

// RuntimeConfigResponse defines model for RuntimeConfigResponse.
type RuntimeConfigResponse struct {
	APIVersion      string             `json:"api_version"`
	FeatureDefaults FeatureDefaults    `json:"feature_defaults"`
	Meta            ResponseMeta       `json:"meta,omitempty"`
	Defaults        ModelDefaults      `json:"model_defaults"`
	Notifications   NotificationConfig `json:"notifications"`
	Observability   Observability      `json:"observability"`
	Providers       []string           `json:"providers"`
	Repos           []ConfigRepo       `json:"repos"`
	Runtime         RuntimeIdentity    `json:"runtime"`
	UI              config.UIConfig    `json:"ui"`
	WorkspaceRoots  []string           `json:"workspace_roots,omitempty"`
}

// RuntimeConfigUpdateResponse defines model for RuntimeConfigUpdateResponse.
type RuntimeConfigUpdateResponse struct {
	APIVersion string       `json:"api_version"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// RuntimeIdentity defines model for RuntimeIdentity.
type RuntimeIdentity struct {
	Config     string `json:"config_path"`
	RuntimeDir string `json:"runtime_dir"`
	StateDir   string `json:"state_dir"`
}

// SSEEvent defines model for SSEEvent.
type SSEEvent struct {
	APIVersion string    `json:"api_version"`
	At         time.Time `json:"at"`
	Epoch      string    `json:"epoch,omitempty"`
	ID         string    `json:"id"`
	Kind       string    `json:"kind"`

	// RecordCount Session's current transcript record count at emission time — the same index space /transcript and /output/stream use. Only set on session.output.activity events.
	RecordCount      int      `json:"record_count,omitempty"`
	Resource         Resource `json:"resource"`
	ResourceVersion  uint64   `json:"resource_version,omitempty"`
	Revision         string   `json:"revision,omitempty"`
	Seq              uint64   `json:"seq,omitempty"`
	SnapshotRequired bool     `json:"snapshot_required"`
	Summary          string   `json:"summary,omitempty"`
}

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	CanAttach        bool             `json:"can_attach"`
	ContextPct       int              `json:"context_percentage,omitempty"`
	Effort           string           `json:"effort,omitempty"`
	EffortSource     string           `json:"effort_source,omitempty"`
	FeatureID        string           `json:"feature_id"`
	ID               string           `json:"id"`
	InitialPrompt    string           `json:"initial_prompt,omitempty"`
	Iteration        int              `json:"iteration,omitempty"`
	Kind             string           `json:"kind"`
	Label            string           `json:"label,omitempty"`
	LogAvailable     bool             `json:"log_available"`
	Model            string           `json:"model,omitempty"`
	PendingControls  []ControlRequest `json:"pending_controls"`
	Phase            string           `json:"phase"`
	Provider         string           `json:"provider,omitempty"`
	Repo             string           `json:"repo,omitempty"`
	SafeError        string           `json:"safe_error,omitempty"`
	StartedAt        time.Time        `json:"started_at"`
	Status           string           `json:"status"`
	TranscriptCursor Cursor           `json:"transcript_cursor"`
	TurnState        string           `json:"turn_state,omitempty"`
	Usage            Usage            `json:"usage"`
}

// SessionDetailResponse defines model for SessionDetailResponse.
type SessionDetailResponse struct {
	APIVersion string        `json:"api_version"`
	Meta       ResponseMeta  `json:"meta,omitempty"`
	Session    SessionDetail `json:"session"`
}

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	APIVersion string           `json:"api_version"`
	Meta       ResponseMeta     `json:"meta,omitempty"`
	Sessions   []SessionSummary `json:"sessions"`
}

// SessionOutputChunk defines model for SessionOutputChunk.
type SessionOutputChunk struct {
	APIVersion string `json:"api_version"`
	Done       bool   `json:"done,omitempty"`

	// Index Transcript row index — the same index space /transcript and session.output.activity's record_count use. Not a byte offset.
	Index     int               `json:"index"`
	Message   TranscriptMessage `json:"message,omitempty"`
	SessionID string            `json:"session_id,omitempty"`
}

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	ContextPct   int       `json:"context_percentage,omitempty"`
	Effort       string    `json:"effort,omitempty"`
	EffortSource string    `json:"effort_source,omitempty"`
	FeatureID    string    `json:"feature_id"`
	ID           string    `json:"id"`
	Iteration    int       `json:"iteration,omitempty"`
	Kind         string    `json:"kind"`
	Label        string    `json:"label,omitempty"`
	Model        string    `json:"model,omitempty"`
	Phase        string    `json:"phase"`
	Provider     string    `json:"provider,omitempty"`
	Repo         string    `json:"repo,omitempty"`
	StartedAt    time.Time `json:"started_at"`
	Status       string    `json:"status"`
	TurnState    string    `json:"turn_state,omitempty"`
	Usage        Usage     `json:"usage"`
}

// Setup defines model for Setup.
type Setup struct {
	Attempt       int                  `json:"attempt,omitempty"`
	CompletedAt   *time.Time           `json:"completed_at,omitempty"`
	LastError     string               `json:"last_error,omitempty"`
	LatestLogPath string               `json:"latest_log_path,omitempty"`
	StartedAt     *time.Time           `json:"started_at,omitempty"`
	Status        string               `json:"status"`
	TaskOrder     []string             `json:"task_order,omitempty"`
	Tasks         map[string]SetupTask `json:"tasks,omitempty"`
}

// SetupTask defines model for SetupTask.
type SetupTask struct {
	Attempt          int        `json:"attempt,omitempty"`
	Branch           string     `json:"branch,omitempty"`
	EndedAt          *time.Time `json:"ended_at,omitempty"`
	Key              string     `json:"key"`
	Kind             string     `json:"kind"`
	Label            string     `json:"label,omitempty"`
	LastError        string     `json:"last_error,omitempty"`
	Path             string     `json:"path,omitempty"`
	Repo             string     `json:"repo,omitempty"`
	SourcePath       string     `json:"source_path,omitempty"`
	StartPoint       string     `json:"start_point,omitempty"`
	StartedAt        *time.Time `json:"started_at,omitempty"`
	Status           string     `json:"status"`
	UseCurrentBranch bool       `json:"use_current_branch,omitempty"`
}

// ShutdownResponse defines model for ShutdownResponse.
type ShutdownResponse struct {
	APIVersion string       `json:"api_version"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Result     string       `json:"result"`
}

// Task defines model for Task.
type Task struct {
	Description  string `json:"description,omitempty"`
	ID           string `json:"id,omitempty"`
	LastToolName string `json:"last_tool_name,omitempty"`
	OutputFile   string `json:"output_file,omitempty"`
	Prompt       string `json:"prompt,omitempty"`
	Status       string `json:"status,omitempty"`
	Summary      string `json:"summary,omitempty"`
	TaskType     string `json:"task_type,omitempty"`
	ToolUseID    string `json:"tool_use_id,omitempty"`
}

// TextContentResponse defines model for TextContentResponse.
type TextContentResponse struct {
	APIVersion string       `json:"api_version"`
	ID         string       `json:"id"`
	Limit      int64        `json:"limit"`
	Meta       ResponseMeta `json:"meta,omitempty"`
	Offset     int64        `json:"offset"`
	Size       int64        `json:"size"`
	Text       string       `json:"text"`
	Truncated  bool         `json:"truncated"`
}

// Timing defines model for Timing.
type Timing struct {
	ByPhase      map[string]int64 `json:"by_phase"`
	TotalSeconds int64            `json:"total_seconds"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Prompt  string `json:"prompt,omitempty"`
	Summary string `json:"summary,omitempty"`
}

// TranscriptMessage defines model for TranscriptMessage.
type TranscriptMessage struct {
	AutoPickConfidence float64     `json:"auto_pick_confidence,omitempty"`
	AutoPickQuestion   string      `json:"auto_pick_question,omitempty"`
	AutoPicked         bool        `json:"auto_picked,omitempty"`
	BlockIndex         int         `json:"block_index,omitempty"`
	FileChange         *FileChange `json:"file_change,omitempty"`
	Index              int         `json:"index"`
	LocallyAppended    bool        `json:"locally_appended,omitempty"`
	Redacted           bool        `json:"redacted,omitempty"`
	Role               string      `json:"role"`
	Status             string      `json:"status,omitempty"`
	Task               *Task       `json:"task,omitempty"`
	Text               string      `json:"text,omitempty"`
	Tool               string      `json:"tool,omitempty"`
	ToolCall           *ToolCall   `json:"tool_call,omitempty"`
	Type               string      `json:"type"`
}

// TranscriptResponse defines model for TranscriptResponse.
type TranscriptResponse struct {
	APIVersion string              `json:"api_version"`
	Cursor     Cursor              `json:"cursor"`
	Messages   []TranscriptMessage `json:"messages"`
	Meta       ResponseMeta        `json:"meta,omitempty"`
}

// Usage defines model for Usage.
type Usage struct {
	CostUSD      float64 `json:"cost_usd,omitempty"`
	InputTokens  int     `json:"input_tokens,omitempty"`
	OutputTokens int     `json:"output_tokens,omitempty"`
}

// VerificationItem defines model for VerificationItem.
type VerificationItem struct {
	Name  string `json:"name"`
	State string `json:"state"`
}

// Warning defines model for Warning.
type Warning struct {
	Code      string `json:"code"`
	FeatureID string `json:"feature_id,omitempty"`
	Message   string `json:"message"`
}

// ArtifactID defines model for ArtifactID.
type ArtifactID = string

// FeatureAction defines model for FeatureAction.
type FeatureAction string

// FeatureID defines model for FeatureID.
type FeatureID = string

// FeatureSubaction defines model for FeatureSubaction.
type FeatureSubaction string

// Limit defines model for Limit.
type Limit = int64

// LogID defines model for LogID.
type LogID = string

// Offset defines model for Offset.
type Offset = int64

// ReviewID defines model for ReviewID.
type ReviewID = string

// RunNumber defines model for RunNumber.
type RunNumber = int

// SessionID defines model for SessionID.
type SessionID = string

// TrustedMutationHeader defines model for TrustedMutationHeader.
type TrustedMutationHeader string

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// JSONMutation defines model for JSONMutation.
type JSONMutation map[string]interface{}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// sSEAccessTokenContextKey is the context key for sseAccessToken security scheme
type sSEAccessTokenContextKey string

// PatchRuntimeConfigJSONBody defines parameters for PatchRuntimeConfig.
type PatchRuntimeConfigJSONBody map[string]interface{}

// PatchRuntimeConfigParams defines parameters for PatchRuntimeConfig.
type PatchRuntimeConfigParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient PatchRuntimeConfigParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// PatchRuntimeConfigParamsXAgenticoClient defines parameters for PatchRuntimeConfig.
type PatchRuntimeConfigParamsXAgenticoClient string

// PutRuntimeConfigJSONBody defines parameters for PutRuntimeConfig.
type PutRuntimeConfigJSONBody map[string]interface{}

// PutRuntimeConfigParams defines parameters for PutRuntimeConfig.
type PutRuntimeConfigParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient PutRuntimeConfigParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// PutRuntimeConfigParamsXAgenticoClient defines parameters for PutRuntimeConfig.
type PutRuntimeConfigParamsXAgenticoClient string

// StreamEventsParams defines parameters for StreamEvents.
type StreamEventsParams struct {
	After       uint64 `form:"after,omitempty" json:"after,omitempty"`
	Epoch       string `form:"epoch,omitempty" json:"epoch,omitempty"`
	HeartbeatMs int    `form:"heartbeat_ms,omitempty" json:"heartbeat_ms,omitempty"`
}

// CreateFeatureJSONBody defines parameters for CreateFeature.
type CreateFeatureJSONBody map[string]interface{}

// CreateFeatureParams defines parameters for CreateFeature.
type CreateFeatureParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient CreateFeatureParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// CreateFeatureParamsXAgenticoClient defines parameters for CreateFeature.
type CreateFeatureParamsXAgenticoClient string

// RunFeatureActionJSONBody defines parameters for RunFeatureAction.
type RunFeatureActionJSONBody map[string]interface{}

// RunFeatureActionParams defines parameters for RunFeatureAction.
type RunFeatureActionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient RunFeatureActionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// RunFeatureActionParamsXAgenticoClient defines parameters for RunFeatureAction.
type RunFeatureActionParamsXAgenticoClient string

// RunFeatureActionParamsAction defines parameters for RunFeatureAction.
type RunFeatureActionParamsAction string

// RunFeatureSubactionJSONBody defines parameters for RunFeatureSubaction.
type RunFeatureSubactionJSONBody map[string]interface{}

// RunFeatureSubactionParams defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient RunFeatureSubactionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// RunFeatureSubactionParamsXAgenticoClient defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParamsXAgenticoClient string

// RunFeatureSubactionParamsAction defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParamsAction string

// RunFeatureSubactionParamsSubaction defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParamsSubaction string

// UpdateFeatureConfigJSONBody defines parameters for UpdateFeatureConfig.
type UpdateFeatureConfigJSONBody map[string]interface{}

// UpdateFeatureConfigParams defines parameters for UpdateFeatureConfig.
type UpdateFeatureConfigParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient UpdateFeatureConfigParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// UpdateFeatureConfigParamsXAgenticoClient defines parameters for UpdateFeatureConfig.
type UpdateFeatureConfigParamsXAgenticoClient string

// CreateReviewSessionJSONBody defines parameters for CreateReviewSession.
type CreateReviewSessionJSONBody map[string]interface{}

// CreateReviewSessionParams defines parameters for CreateReviewSession.
type CreateReviewSessionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient CreateReviewSessionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// CreateReviewSessionParamsXAgenticoClient defines parameters for CreateReviewSession.
type CreateReviewSessionParamsXAgenticoClient string

// SubmitReviewSessionDecisionParams defines parameters for SubmitReviewSessionDecision.
type SubmitReviewSessionDecisionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient SubmitReviewSessionDecisionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// SubmitReviewSessionDecisionParamsXAgenticoClient defines parameters for SubmitReviewSessionDecision.
type SubmitReviewSessionDecisionParamsXAgenticoClient string

// SaveReviewDraftParams defines parameters for SaveReviewDraft.
type SaveReviewDraftParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient SaveReviewDraftParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// SaveReviewDraftParamsXAgenticoClient defines parameters for SaveReviewDraft.
type SaveReviewDraftParamsXAgenticoClient string

// GetArtifactContentParams defines parameters for GetArtifactContent.
type GetArtifactContentParams struct {
	Offset Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetRunLogContentParams defines parameters for GetRunLogContent.
type GetRunLogContentParams struct {
	Offset Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// AnswerPermissionParams defines parameters for AnswerPermission.
type AnswerPermissionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient AnswerPermissionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// AnswerPermissionParamsXAgenticoClient defines parameters for AnswerPermission.
type AnswerPermissionParamsXAgenticoClient string

// AnswerAskUserPromptJSONBody defines parameters for AnswerAskUserPrompt.
type AnswerAskUserPromptJSONBody map[string]interface{}

// AnswerAskUserPromptParams defines parameters for AnswerAskUserPrompt.
type AnswerAskUserPromptParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient AnswerAskUserPromptParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// AnswerAskUserPromptParamsXAgenticoClient defines parameters for AnswerAskUserPrompt.
type AnswerAskUserPromptParamsXAgenticoClient string

// StartChatPromptJSONBody defines parameters for StartChatPrompt.
type StartChatPromptJSONBody map[string]interface{}

// StartChatPromptParams defines parameters for StartChatPrompt.
type StartChatPromptParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient StartChatPromptParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// StartChatPromptParamsXAgenticoClient defines parameters for StartChatPrompt.
type StartChatPromptParamsXAgenticoClient string

// SendHelpPromptJSONBody defines parameters for SendHelpPrompt.
type SendHelpPromptJSONBody map[string]interface{}

// SendHelpPromptParams defines parameters for SendHelpPrompt.
type SendHelpPromptParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient SendHelpPromptParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// SendHelpPromptParamsXAgenticoClient defines parameters for SendHelpPrompt.
type SendHelpPromptParamsXAgenticoClient string

// ExecuteRecoveryActionsJSONBody defines parameters for ExecuteRecoveryActions.
type ExecuteRecoveryActionsJSONBody map[string]interface{}

// ExecuteRecoveryActionsParams defines parameters for ExecuteRecoveryActions.
type ExecuteRecoveryActionsParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient ExecuteRecoveryActionsParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// ExecuteRecoveryActionsParamsXAgenticoClient defines parameters for ExecuteRecoveryActions.
type ExecuteRecoveryActionsParamsXAgenticoClient string

// StreamSessionOutputParams defines parameters for StreamSessionOutput.
type StreamSessionOutputParams struct {
	// From Resume position expressed as a transcript row index (the same index space `/transcript` uses), not a byte offset.
	From int64 `form:"from,omitempty" json:"from,omitempty"`
}

// GetSessionTranscriptParams defines parameters for GetSessionTranscript.
type GetSessionTranscriptParams struct {
	Offset int64 `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ShutdownRuntimeJSONBody defines parameters for ShutdownRuntime.
type ShutdownRuntimeJSONBody map[string]interface{}

// ShutdownRuntimeParams defines parameters for ShutdownRuntime.
type ShutdownRuntimeParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient ShutdownRuntimeParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// ShutdownRuntimeParamsXAgenticoClient defines parameters for ShutdownRuntime.
type ShutdownRuntimeParamsXAgenticoClient string

// PatchRuntimeConfigJSONRequestBody defines body for PatchRuntimeConfig for application/json ContentType.
type PatchRuntimeConfigJSONRequestBody PatchRuntimeConfigJSONBody

// PutRuntimeConfigJSONRequestBody defines body for PutRuntimeConfig for application/json ContentType.
type PutRuntimeConfigJSONRequestBody PutRuntimeConfigJSONBody

// CreateFeatureJSONRequestBody defines body for CreateFeature for application/json ContentType.
type CreateFeatureJSONRequestBody CreateFeatureJSONBody

// RunFeatureActionJSONRequestBody defines body for RunFeatureAction for application/json ContentType.
type RunFeatureActionJSONRequestBody RunFeatureActionJSONBody

// RunFeatureSubactionJSONRequestBody defines body for RunFeatureSubaction for application/json ContentType.
type RunFeatureSubactionJSONRequestBody RunFeatureSubactionJSONBody

// UpdateFeatureConfigJSONRequestBody defines body for UpdateFeatureConfig for application/json ContentType.
type UpdateFeatureConfigJSONRequestBody UpdateFeatureConfigJSONBody

// CreateReviewSessionJSONRequestBody defines body for CreateReviewSession for application/json ContentType.
type CreateReviewSessionJSONRequestBody CreateReviewSessionJSONBody

// SubmitReviewSessionDecisionJSONRequestBody defines body for SubmitReviewSessionDecision for application/json ContentType.
type SubmitReviewSessionDecisionJSONRequestBody = ReviewSessionDecisionRequest

// SaveReviewDraftJSONRequestBody defines body for SaveReviewDraft for application/json ContentType.
type SaveReviewDraftJSONRequestBody = ReviewDraftUpdateRequest

// AnswerPermissionJSONRequestBody defines body for AnswerPermission for application/json ContentType.
type AnswerPermissionJSONRequestBody = PermissionAnswerSchema

// AnswerAskUserPromptJSONRequestBody defines body for AnswerAskUserPrompt for application/json ContentType.
type AnswerAskUserPromptJSONRequestBody AnswerAskUserPromptJSONBody

// StartChatPromptJSONRequestBody defines body for StartChatPrompt for application/json ContentType.
type StartChatPromptJSONRequestBody StartChatPromptJSONBody

// SendHelpPromptJSONRequestBody defines body for SendHelpPrompt for application/json ContentType.
type SendHelpPromptJSONRequestBody SendHelpPromptJSONBody

// ExecuteRecoveryActionsJSONRequestBody defines body for ExecuteRecoveryActions for application/json ContentType.
type ExecuteRecoveryActionsJSONRequestBody ExecuteRecoveryActionsJSONBody

// ShutdownRuntimeJSONRequestBody defines body for ShutdownRuntime for application/json ContentType.
type ShutdownRuntimeJSONRequestBody ShutdownRuntimeJSONBody
