// Copyright 2026 DoorDash, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package serverapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package serverapi

import (
	"encoding/json"
	"fmt"
	"time"
)

const (
	BearerAuthScopes     bearerAuthContextKey     = "bearerAuth.Scopes"
	SseAccessTokenScopes sSEAccessTokenContextKey = "sseAccessToken.Scopes"
)

// Defines values for FeatureAction.
const (
	FeatureActionCleanup        FeatureAction = "cleanup"
	FeatureActionDelete         FeatureAction = "delete"
	FeatureActionMarkDone       FeatureAction = "mark-done"
	FeatureActionMerge          FeatureAction = "merge"
	FeatureActionPauseStop      FeatureAction = "pause-stop"
	FeatureActionPublish        FeatureAction = "publish"
	FeatureActionRebase         FeatureAction = "rebase"
	FeatureActionRefactor       FeatureAction = "refactor"
	FeatureActionRestart        FeatureAction = "restart"
	FeatureActionResume         FeatureAction = "resume"
	FeatureActionRetry          FeatureAction = "retry"
	FeatureActionReviewComments FeatureAction = "review-comments"
	FeatureActionRewind         FeatureAction = "rewind"
	FeatureActionStart          FeatureAction = "start"
	FeatureActionTweak          FeatureAction = "tweak"
)

// Valid indicates whether the value is a known member of the FeatureAction enum.
func (e FeatureAction) Valid() bool {
	switch e {
	case FeatureActionCleanup:
		return true
	case FeatureActionDelete:
		return true
	case FeatureActionMarkDone:
		return true
	case FeatureActionMerge:
		return true
	case FeatureActionPauseStop:
		return true
	case FeatureActionPublish:
		return true
	case FeatureActionRebase:
		return true
	case FeatureActionRefactor:
		return true
	case FeatureActionRestart:
		return true
	case FeatureActionResume:
		return true
	case FeatureActionRetry:
		return true
	case FeatureActionReviewComments:
		return true
	case FeatureActionRewind:
		return true
	case FeatureActionStart:
		return true
	case FeatureActionTweak:
		return true
	default:
		return false
	}
}

// Defines values for FeatureSubaction.
const (
	FeatureSubactionDescription FeatureSubaction = "description"
	FeatureSubactionFetch       FeatureSubaction = "fetch"
	FeatureSubactionFinish      FeatureSubaction = "finish"
	FeatureSubactionRestart     FeatureSubaction = "restart"
)

// Valid indicates whether the value is a known member of the FeatureSubaction enum.
func (e FeatureSubaction) Valid() bool {
	switch e {
	case FeatureSubactionDescription:
		return true
	case FeatureSubactionFetch:
		return true
	case FeatureSubactionFinish:
		return true
	case FeatureSubactionRestart:
		return true
	default:
		return false
	}
}

// Defines values for TrustedMutationHeader.
const (
	TrustedMutationHeaderLocal TrustedMutationHeader = "local"
)

// Valid indicates whether the value is a known member of the TrustedMutationHeader enum.
func (e TrustedMutationHeader) Valid() bool {
	switch e {
	case TrustedMutationHeaderLocal:
		return true
	default:
		return false
	}
}

// Defines values for PatchRuntimeConfigParamsXAgenticoClient.
const (
	PatchRuntimeConfigParamsXAgenticoClientLocal PatchRuntimeConfigParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the PatchRuntimeConfigParamsXAgenticoClient enum.
func (e PatchRuntimeConfigParamsXAgenticoClient) Valid() bool {
	switch e {
	case PatchRuntimeConfigParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for PutRuntimeConfigParamsXAgenticoClient.
const (
	PutRuntimeConfigParamsXAgenticoClientLocal PutRuntimeConfigParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the PutRuntimeConfigParamsXAgenticoClient enum.
func (e PutRuntimeConfigParamsXAgenticoClient) Valid() bool {
	switch e {
	case PutRuntimeConfigParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for CreateFeatureParamsXAgenticoClient.
const (
	CreateFeatureParamsXAgenticoClientLocal CreateFeatureParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the CreateFeatureParamsXAgenticoClient enum.
func (e CreateFeatureParamsXAgenticoClient) Valid() bool {
	switch e {
	case CreateFeatureParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureActionParamsXAgenticoClient.
const (
	RunFeatureActionParamsXAgenticoClientLocal RunFeatureActionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the RunFeatureActionParamsXAgenticoClient enum.
func (e RunFeatureActionParamsXAgenticoClient) Valid() bool {
	switch e {
	case RunFeatureActionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureActionParamsAction.
const (
	RunFeatureActionParamsActionCleanup        RunFeatureActionParamsAction = "cleanup"
	RunFeatureActionParamsActionDelete         RunFeatureActionParamsAction = "delete"
	RunFeatureActionParamsActionMarkDone       RunFeatureActionParamsAction = "mark-done"
	RunFeatureActionParamsActionMerge          RunFeatureActionParamsAction = "merge"
	RunFeatureActionParamsActionPauseStop      RunFeatureActionParamsAction = "pause-stop"
	RunFeatureActionParamsActionPublish        RunFeatureActionParamsAction = "publish"
	RunFeatureActionParamsActionRebase         RunFeatureActionParamsAction = "rebase"
	RunFeatureActionParamsActionRefactor       RunFeatureActionParamsAction = "refactor"
	RunFeatureActionParamsActionRestart        RunFeatureActionParamsAction = "restart"
	RunFeatureActionParamsActionResume         RunFeatureActionParamsAction = "resume"
	RunFeatureActionParamsActionRetry          RunFeatureActionParamsAction = "retry"
	RunFeatureActionParamsActionReviewComments RunFeatureActionParamsAction = "review-comments"
	RunFeatureActionParamsActionRewind         RunFeatureActionParamsAction = "rewind"
	RunFeatureActionParamsActionStart          RunFeatureActionParamsAction = "start"
	RunFeatureActionParamsActionTweak          RunFeatureActionParamsAction = "tweak"
)

// Valid indicates whether the value is a known member of the RunFeatureActionParamsAction enum.
func (e RunFeatureActionParamsAction) Valid() bool {
	switch e {
	case RunFeatureActionParamsActionCleanup:
		return true
	case RunFeatureActionParamsActionDelete:
		return true
	case RunFeatureActionParamsActionMarkDone:
		return true
	case RunFeatureActionParamsActionMerge:
		return true
	case RunFeatureActionParamsActionPauseStop:
		return true
	case RunFeatureActionParamsActionPublish:
		return true
	case RunFeatureActionParamsActionRebase:
		return true
	case RunFeatureActionParamsActionRefactor:
		return true
	case RunFeatureActionParamsActionRestart:
		return true
	case RunFeatureActionParamsActionResume:
		return true
	case RunFeatureActionParamsActionRetry:
		return true
	case RunFeatureActionParamsActionReviewComments:
		return true
	case RunFeatureActionParamsActionRewind:
		return true
	case RunFeatureActionParamsActionStart:
		return true
	case RunFeatureActionParamsActionTweak:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureSubactionParamsXAgenticoClient.
const (
	RunFeatureSubactionParamsXAgenticoClientLocal RunFeatureSubactionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the RunFeatureSubactionParamsXAgenticoClient enum.
func (e RunFeatureSubactionParamsXAgenticoClient) Valid() bool {
	switch e {
	case RunFeatureSubactionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureSubactionParamsAction.
const (
	RunFeatureSubactionParamsActionCleanup        RunFeatureSubactionParamsAction = "cleanup"
	RunFeatureSubactionParamsActionDelete         RunFeatureSubactionParamsAction = "delete"
	RunFeatureSubactionParamsActionMarkDone       RunFeatureSubactionParamsAction = "mark-done"
	RunFeatureSubactionParamsActionMerge          RunFeatureSubactionParamsAction = "merge"
	RunFeatureSubactionParamsActionPauseStop      RunFeatureSubactionParamsAction = "pause-stop"
	RunFeatureSubactionParamsActionPublish        RunFeatureSubactionParamsAction = "publish"
	RunFeatureSubactionParamsActionRebase         RunFeatureSubactionParamsAction = "rebase"
	RunFeatureSubactionParamsActionRefactor       RunFeatureSubactionParamsAction = "refactor"
	RunFeatureSubactionParamsActionRestart        RunFeatureSubactionParamsAction = "restart"
	RunFeatureSubactionParamsActionResume         RunFeatureSubactionParamsAction = "resume"
	RunFeatureSubactionParamsActionRetry          RunFeatureSubactionParamsAction = "retry"
	RunFeatureSubactionParamsActionReviewComments RunFeatureSubactionParamsAction = "review-comments"
	RunFeatureSubactionParamsActionRewind         RunFeatureSubactionParamsAction = "rewind"
	RunFeatureSubactionParamsActionStart          RunFeatureSubactionParamsAction = "start"
	RunFeatureSubactionParamsActionTweak          RunFeatureSubactionParamsAction = "tweak"
)

// Valid indicates whether the value is a known member of the RunFeatureSubactionParamsAction enum.
func (e RunFeatureSubactionParamsAction) Valid() bool {
	switch e {
	case RunFeatureSubactionParamsActionCleanup:
		return true
	case RunFeatureSubactionParamsActionDelete:
		return true
	case RunFeatureSubactionParamsActionMarkDone:
		return true
	case RunFeatureSubactionParamsActionMerge:
		return true
	case RunFeatureSubactionParamsActionPauseStop:
		return true
	case RunFeatureSubactionParamsActionPublish:
		return true
	case RunFeatureSubactionParamsActionRebase:
		return true
	case RunFeatureSubactionParamsActionRefactor:
		return true
	case RunFeatureSubactionParamsActionRestart:
		return true
	case RunFeatureSubactionParamsActionResume:
		return true
	case RunFeatureSubactionParamsActionRetry:
		return true
	case RunFeatureSubactionParamsActionReviewComments:
		return true
	case RunFeatureSubactionParamsActionRewind:
		return true
	case RunFeatureSubactionParamsActionStart:
		return true
	case RunFeatureSubactionParamsActionTweak:
		return true
	default:
		return false
	}
}

// Defines values for RunFeatureSubactionParamsSubaction.
const (
	Description RunFeatureSubactionParamsSubaction = "description"
	Fetch       RunFeatureSubactionParamsSubaction = "fetch"
	Finish      RunFeatureSubactionParamsSubaction = "finish"
	Restart     RunFeatureSubactionParamsSubaction = "restart"
)

// Valid indicates whether the value is a known member of the RunFeatureSubactionParamsSubaction enum.
func (e RunFeatureSubactionParamsSubaction) Valid() bool {
	switch e {
	case Description:
		return true
	case Fetch:
		return true
	case Finish:
		return true
	case Restart:
		return true
	default:
		return false
	}
}

// Defines values for UpdateFeatureConfigParamsXAgenticoClient.
const (
	UpdateFeatureConfigParamsXAgenticoClientLocal UpdateFeatureConfigParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the UpdateFeatureConfigParamsXAgenticoClient enum.
func (e UpdateFeatureConfigParamsXAgenticoClient) Valid() bool {
	switch e {
	case UpdateFeatureConfigParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for ToggleInputNotificationsLegacyParamsXAgenticoClient.
const (
	ToggleInputNotificationsLegacyParamsXAgenticoClientLocal ToggleInputNotificationsLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the ToggleInputNotificationsLegacyParamsXAgenticoClient enum.
func (e ToggleInputNotificationsLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case ToggleInputNotificationsLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for InterruptFeatureLegacyParamsXAgenticoClient.
const (
	InterruptFeatureLegacyParamsXAgenticoClientLocal InterruptFeatureLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the InterruptFeatureLegacyParamsXAgenticoClient enum.
func (e InterruptFeatureLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case InterruptFeatureLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for AnswerNeedUserInputLegacyParamsXAgenticoClient.
const (
	AnswerNeedUserInputLegacyParamsXAgenticoClientLocal AnswerNeedUserInputLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the AnswerNeedUserInputLegacyParamsXAgenticoClient enum.
func (e AnswerNeedUserInputLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case AnswerNeedUserInputLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for DraftNeedUserInputLegacyParamsXAgenticoClient.
const (
	DraftNeedUserInputLegacyParamsXAgenticoClientLocal DraftNeedUserInputLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the DraftNeedUserInputLegacyParamsXAgenticoClient enum.
func (e DraftNeedUserInputLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case DraftNeedUserInputLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for RestartFeatureLegacyParamsXAgenticoClient.
const (
	RestartFeatureLegacyParamsXAgenticoClientLocal RestartFeatureLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the RestartFeatureLegacyParamsXAgenticoClient enum.
func (e RestartFeatureLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case RestartFeatureLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for ResumeFeatureLegacyParamsXAgenticoClient.
const (
	ResumeFeatureLegacyParamsXAgenticoClientLocal ResumeFeatureLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the ResumeFeatureLegacyParamsXAgenticoClient enum.
func (e ResumeFeatureLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case ResumeFeatureLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for SubmitReviewDecisionLegacyParamsXAgenticoClient.
const (
	SubmitReviewDecisionLegacyParamsXAgenticoClientLocal SubmitReviewDecisionLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the SubmitReviewDecisionLegacyParamsXAgenticoClient enum.
func (e SubmitReviewDecisionLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case SubmitReviewDecisionLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for StartFeatureLegacyParamsXAgenticoClient.
const (
	StartFeatureLegacyParamsXAgenticoClientLocal StartFeatureLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the StartFeatureLegacyParamsXAgenticoClient enum.
func (e StartFeatureLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case StartFeatureLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for StopFeatureLegacyParamsXAgenticoClient.
const (
	StopFeatureLegacyParamsXAgenticoClientLocal StopFeatureLegacyParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the StopFeatureLegacyParamsXAgenticoClient enum.
func (e StopFeatureLegacyParamsXAgenticoClient) Valid() bool {
	switch e {
	case StopFeatureLegacyParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for AnswerPermissionParamsXAgenticoClient.
const (
	AnswerPermissionParamsXAgenticoClientLocal AnswerPermissionParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the AnswerPermissionParamsXAgenticoClient enum.
func (e AnswerPermissionParamsXAgenticoClient) Valid() bool {
	switch e {
	case AnswerPermissionParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for AnswerAskUserPromptParamsXAgenticoClient.
const (
	AnswerAskUserPromptParamsXAgenticoClientLocal AnswerAskUserPromptParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the AnswerAskUserPromptParamsXAgenticoClient enum.
func (e AnswerAskUserPromptParamsXAgenticoClient) Valid() bool {
	switch e {
	case AnswerAskUserPromptParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for StartChatPromptParamsXAgenticoClient.
const (
	StartChatPromptParamsXAgenticoClientLocal StartChatPromptParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the StartChatPromptParamsXAgenticoClient enum.
func (e StartChatPromptParamsXAgenticoClient) Valid() bool {
	switch e {
	case StartChatPromptParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for SendHelpPromptParamsXAgenticoClient.
const (
	SendHelpPromptParamsXAgenticoClientLocal SendHelpPromptParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the SendHelpPromptParamsXAgenticoClient enum.
func (e SendHelpPromptParamsXAgenticoClient) Valid() bool {
	switch e {
	case SendHelpPromptParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for ExecuteRecoveryActionsParamsXAgenticoClient.
const (
	ExecuteRecoveryActionsParamsXAgenticoClientLocal ExecuteRecoveryActionsParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the ExecuteRecoveryActionsParamsXAgenticoClient enum.
func (e ExecuteRecoveryActionsParamsXAgenticoClient) Valid() bool {
	switch e {
	case ExecuteRecoveryActionsParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Defines values for ShutdownRuntimeParamsXAgenticoClient.
const (
	ShutdownRuntimeParamsXAgenticoClientLocal ShutdownRuntimeParamsXAgenticoClient = "local"
)

// Valid indicates whether the value is a known member of the ShutdownRuntimeParamsXAgenticoClient enum.
func (e ShutdownRuntimeParamsXAgenticoClient) Valid() bool {
	switch e {
	case ShutdownRuntimeParamsXAgenticoClientLocal:
		return true
	default:
		return false
	}
}

// Action defines model for Action.
type Action struct {
	DisabledReasons []ActionDisabledReason `json:"disabled_reasons,omitempty"`
	Enabled         bool                   `json:"enabled"`
	ID              string                 `json:"id"`
	RequiredInputs  []ActionInput          `json:"required_inputs"`
	Scope           ActionScope            `json:"scope"`
}

// ActionDisabledReason defines model for ActionDisabledReason.
type ActionDisabledReason struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ActionInput defines model for ActionInput.
type ActionInput struct {
	Kind      string   `json:"kind"`
	MaxLength int      `json:"max_length,omitempty"`
	Name      string   `json:"name"`
	Options   []string `json:"options,omitempty"`
	Required  bool     `json:"required"`
}

// ActionResponse defines model for ActionResponse.
type ActionResponse = JSONResponse

// ActionScope defines model for ActionScope.
type ActionScope struct {
	CycleType     string `json:"cycle_type,omitempty"`
	RepoSelection string `json:"repo_selection,omitempty"`
	Type          string `json:"type"`
}

// ArtifactListResponse defines model for ArtifactListResponse.
type ArtifactListResponse = JSONResponse

// AskUserOption defines model for AskUserOption.
type AskUserOption struct {
	Confidence  *float64 `json:"confidence,omitempty"`
	Description string   `json:"description,omitempty"`
	Label       string   `json:"label,omitempty"`
}

// AskUserQuestion defines model for AskUserQuestion.
type AskUserQuestion struct {
	Header      string          `json:"header,omitempty"`
	MultiSelect bool            `json:"multi_select,omitempty"`
	Options     []AskUserOption `json:"options,omitempty"`
	Question    string          `json:"question,omitempty"`
}

// Checkpoints defines model for Checkpoints.
type Checkpoints struct {
	DesignReview    bool `json:"design_review"`
	DraftPublish    bool `json:"draft_publish"`
	InquiryReview   bool `json:"inquiry_review"`
	ManualPublish   bool `json:"manual_publish"`
	PhasePlanReview bool `json:"phase_plan_review"`
	ResearchReview  bool `json:"research_review"`
	RoadmapReview   bool `json:"roadmap_review"`
}

// ControlRequest defines model for ControlRequest.
type ControlRequest struct {
	FeatureID string                 `json:"feature_id,omitempty"`
	Input     map[string]interface{} `json:"input,omitempty"`
	Phase     string                 `json:"phase,omitempty"`
	Questions []AskUserQuestion      `json:"questions,omitempty"`
	RequestID string                 `json:"request_id"`
	SessionID string                 `json:"session_id,omitempty"`
	Status    string                 `json:"status"`
	Summary   string                 `json:"summary,omitempty"`
	ToolName  string                 `json:"tool_name"`
}

// Cost defines model for Cost.
type Cost struct {
	ByPhase  map[string]float64 `json:"by_phase"`
	TotalUSD float64            `json:"total_usd"`
}

// Cursor defines model for Cursor.
type Cursor struct {
	End   int `json:"end"`
	Start int `json:"start"`
	Total int `json:"total"`
}

// Cycle defines model for Cycle.
type Cycle struct {
	Count     int    `json:"count,omitempty"`
	Iteration int    `json:"iteration,omitempty"`
	Status    string `json:"status,omitempty"`
	Type      string `json:"type,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string                 `json:"code"`
	Message string                 `json:"message"`
	Status  int                    `json:"status"`
	Target  map[string]interface{} `json:"target,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	APIVersion string `json:"api_version"`
	Error      Error  `json:"error"`
}

// Failure defines model for Failure.
type Failure struct {
	Message string `json:"message,omitempty"`
	Type    string `json:"type,omitempty"`
}

// FeatureConfigResponse defines model for FeatureConfigResponse.
type FeatureConfigResponse = JSONResponse

// FeatureDetail defines model for FeatureDetail.
type FeatureDetail struct {
	Actions         []Action          `json:"actions"`
	ActiveRun       int               `json:"active_run"`
	ActiveRunDetail RunSummary        `json:"active_run_detail,omitempty"`
	CacheRevalidate string            `json:"cache_revalidate"`
	Checkpoints     Checkpoints       `json:"checkpoints"`
	Cost            Cost              `json:"cost"`
	CreatedAt       time.Time         `json:"created_at"`
	CurrentPhase    string            `json:"current_phase"`
	Cycle           Cycle             `json:"cycle,omitempty"`
	Description     string            `json:"description,omitempty"`
	Failure         Failure           `json:"failure,omitempty"`
	HistoricalRuns  []RunSummary      `json:"historical_runs"`
	ID              string            `json:"id"`
	Models          ModelDefaults     `json:"models"`
	Name            string            `json:"name"`
	NeedUserInput   NeedUserInputGate `json:"need_user_input,omitempty"`
	Pipeline        string            `json:"pipeline,omitempty"`
	Progress        FeatureProgress   `json:"progress"`
	RepoStatus      []RepoStatus      `json:"repo_status"`
	Repos           []string          `json:"repos"`
	ReviewGate      ReviewGate        `json:"review_gate"`
	Revision        string            `json:"revision"`
	RunCount        int               `json:"run_count"`
	Slug            string            `json:"slug"`
	Status          string            `json:"status"`
	Summary         string            `json:"summary,omitempty"`
	Timing          Timing            `json:"timing"`
	Warnings        []Warning         `json:"warnings,omitempty"`
}

// FeatureDetailResponse defines model for FeatureDetailResponse.
type FeatureDetailResponse struct {
	APIVersion           string                 `json:"api_version"`
	Feature              FeatureDetail          `json:"feature"`
	Meta                 ResponseMeta           `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FeatureListResponse defines model for FeatureListResponse.
type FeatureListResponse struct {
	APIVersion           string                 `json:"api_version"`
	Features             []FeatureSummary       `json:"features"`
	Meta                 ResponseMeta           `json:"meta,omitempty"`
	Warnings             []Warning              `json:"warnings,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FeatureProgress defines model for FeatureProgress.
type FeatureProgress struct {
	CurrentIteration    int    `json:"current_iteration,omitempty"`
	CurrentPhaseStatus  string `json:"current_phase_status,omitempty"`
	CurrentRoadmapPhase int    `json:"current_roadmap_phase,omitempty"`
	TotalRoadmapPhases  int    `json:"total_roadmap_phases,omitempty"`
}

// FeatureSummary defines model for FeatureSummary.
type FeatureSummary struct {
	ActiveRun    int             `json:"active_run"`
	Checkpoints  Checkpoints     `json:"checkpoints"`
	CreatedAt    time.Time       `json:"created_at"`
	CurrentPhase string          `json:"current_phase"`
	Cycle        *Cycle          `json:"cycle,omitempty"`
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Progress     FeatureProgress `json:"progress"`
	Repos        []string        `json:"repos"`
	RunCount     int             `json:"run_count"`
	Slug         string          `json:"slug"`
	Status       string          `json:"status"`
	Warnings     []Warning       `json:"warnings,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse = JSONResponse

// JSONResponse defines model for JSONResponse.
type JSONResponse struct {
	APIVersion           string                 `json:"api_version"`
	Meta                 ResponseMeta           `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LivePreviewResponse defines model for LivePreviewResponse.
type LivePreviewResponse = JSONResponse

// ModelCatalogResponse defines model for ModelCatalogResponse.
type ModelCatalogResponse = JSONResponse

// ModelDefaults defines model for ModelDefaults.
type ModelDefaults struct {
	Implementation string `json:"implementation,omitempty"`
	Inquiry        string `json:"inquiry,omitempty"`
	KbBuild        string `json:"kb_build,omitempty"`
	Planning       string `json:"planning,omitempty"`
	Research       string `json:"research,omitempty"`
	Review         string `json:"review,omitempty"`
	Utilities      string `json:"utilities,omitempty"`
}

// NeedUserInputGate defines model for NeedUserInputGate.
type NeedUserInputGate struct {
	FeatureID string `json:"feature_id,omitempty"`
	Iteration int    `json:"iteration,omitempty"`
	Open      bool   `json:"open"`
	Scope     string `json:"scope,omitempty"`
}

// PermissionSnapshotResponse defines model for PermissionSnapshotResponse.
type PermissionSnapshotResponse = JSONResponse

// PromptSnapshotResponse defines model for PromptSnapshotResponse.
type PromptSnapshotResponse = JSONResponse

// RecoverySnapshotResponse defines model for RecoverySnapshotResponse.
type RecoverySnapshotResponse = JSONResponse

// RepoStatus defines model for RepoStatus.
type RepoStatus struct {
	ConflictFiles []string `json:"conflict_files,omitempty"`
	CycleStatus   string   `json:"cycle_status,omitempty"`
	CycleType     string   `json:"cycle_type,omitempty"`
	Freshness     string   `json:"freshness,omitempty"`
	LastError     string   `json:"last_error,omitempty"`
	Name          string   `json:"name"`
	PRURL         string   `json:"pr_url,omitempty"`
	Publishable   bool     `json:"publishable"`
	RebaseStatus  string   `json:"rebase_status,omitempty"`
	RebaseTarget  string   `json:"rebase_target,omitempty"`
	Touched       bool     `json:"touched"`
}

// Resource defines model for Resource.
type Resource struct {
	FeatureID string `json:"feature_id,omitempty"`
	ID        string `json:"id,omitempty"`
	Phase     string `json:"phase,omitempty"`
	Type      string `json:"type"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	AsOfSeq     uint64    `json:"as_of_seq"`
	GeneratedAt time.Time `json:"generated_at"`
	Revision    string    `json:"revision"`
}

// ReviewGate defines model for ReviewGate.
type ReviewGate struct {
	ReviewFixing      bool              `json:"review_fixing"`
	ReviewingGate     bool              `json:"reviewing_gate"`
	ValidatingPlan    bool              `json:"validating_plan"`
	ValidatorStatuses map[string]string `json:"validator_statuses,omitempty"`
}

// RunSummary defines model for RunSummary.
type RunSummary struct {
	ArtifactCount                   int       `json:"artifact_count"`
	CurrentPhase                    string    `json:"current_phase,omitempty"`
	HasNeedUserGate                 bool      `json:"has_need_user_gate,omitempty"`
	IsRewind                        bool      `json:"is_rewind,omitempty"`
	Iteration                       int       `json:"iteration,omitempty"`
	PendingReviewPhase              string    `json:"pending_review_phase,omitempty"`
	PendingRewindReviewRoadmapPhase int       `json:"pending_rewind_review_roadmap_phase,omitempty"`
	PhaseStatus                     string    `json:"phase_status,omitempty"`
	RoadmapPhase                    int       `json:"roadmap_phase,omitempty"`
	RoadmapTotal                    int       `json:"roadmap_total,omitempty"`
	RunNumber                       int       `json:"run_number"`
	SealReason                      string    `json:"seal_reason,omitempty"`
	SealedAt                        time.Time `json:"sealed_at,omitempty"`

	// Setup SetupDTO — untyped for now (see the tracked JSONResponse remainder note above; nested setup/task detail is not yet typed).
	Setup     map[string]interface{} `json:"setup,omitempty"`
	StartedAt time.Time              `json:"started_at,omitempty"`
}

// RuntimeConfigResponse defines model for RuntimeConfigResponse.
type RuntimeConfigResponse = JSONResponse

// SSEEvent defines model for SSEEvent.
type SSEEvent struct {
	APIVersion string    `json:"api_version"`
	At         time.Time `json:"at"`
	Epoch      string    `json:"epoch,omitempty"`
	ID         string    `json:"id"`
	Kind       string    `json:"kind"`

	// RecordCount Session's current transcript record count at emission time — the same index space /transcript and /output/stream use. Only set on session.output.activity events.
	RecordCount      int      `json:"record_count,omitempty"`
	Resource         Resource `json:"resource"`
	ResourceVersion  uint64   `json:"resource_version,omitempty"`
	Revision         string   `json:"revision,omitempty"`
	Seq              uint64   `json:"seq,omitempty"`
	SnapshotRequired bool     `json:"snapshot_required"`
	Summary          string   `json:"summary,omitempty"`
}

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	CanAttach        bool             `json:"can_attach"`
	ContextPct       int              `json:"context_percentage,omitempty"`
	FeatureID        string           `json:"feature_id"`
	ID               string           `json:"id"`
	InitialPrompt    string           `json:"initial_prompt,omitempty"`
	Iteration        int              `json:"iteration,omitempty"`
	Kind             string           `json:"kind"`
	Label            string           `json:"label,omitempty"`
	LogAvailable     bool             `json:"log_available"`
	Model            string           `json:"model,omitempty"`
	PendingControls  []ControlRequest `json:"pending_controls"`
	Phase            string           `json:"phase"`
	Provider         string           `json:"provider,omitempty"`
	Repo             string           `json:"repo,omitempty"`
	SafeError        string           `json:"safe_error,omitempty"`
	StartedAt        time.Time        `json:"started_at"`
	Status           string           `json:"status"`
	TranscriptCursor Cursor           `json:"transcript_cursor"`
	TurnState        string           `json:"turn_state,omitempty"`
	Usage            Usage            `json:"usage"`
}

// SessionDetailResponse defines model for SessionDetailResponse.
type SessionDetailResponse struct {
	APIVersion           string                 `json:"api_version"`
	Meta                 ResponseMeta           `json:"meta,omitempty"`
	Session              SessionDetail          `json:"session"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	APIVersion           string                 `json:"api_version"`
	Meta                 ResponseMeta           `json:"meta,omitempty"`
	Sessions             []SessionSummary       `json:"sessions"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SessionOutputChunk defines model for SessionOutputChunk.
type SessionOutputChunk struct {
	Done bool `json:"done,omitempty"`

	// Index Transcript row index — the same index space /transcript and session.output.activity's record_count use. Not a byte offset.
	Index int `json:"index"`

	// Message A TranscriptMessageDTO row (see the /transcript response).
	Message   map[string]interface{} `json:"message,omitempty"`
	SessionID string                 `json:"session_id,omitempty"`
}

// SessionOutputResponse defines model for SessionOutputResponse.
type SessionOutputResponse struct {
	APIVersion           string                 `json:"api_version"`
	Data                 string                 `json:"data"`
	Done                 bool                   `json:"done"`
	Meta                 ResponseMeta           `json:"meta,omitempty"`
	NextOffset           int64                  `json:"next_offset"`
	Offset               int64                  `json:"offset"`
	SessionID            string                 `json:"session_id"`
	Size                 int64                  `json:"size"`
	Truncated            bool                   `json:"truncated"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	ContextPct int       `json:"context_percentage,omitempty"`
	FeatureID  string    `json:"feature_id"`
	ID         string    `json:"id"`
	Iteration  int       `json:"iteration,omitempty"`
	Kind       string    `json:"kind"`
	Label      string    `json:"label,omitempty"`
	Model      string    `json:"model,omitempty"`
	Phase      string    `json:"phase"`
	Provider   string    `json:"provider,omitempty"`
	Repo       string    `json:"repo,omitempty"`
	StartedAt  time.Time `json:"started_at"`
	Status     string    `json:"status"`
	TurnState  string    `json:"turn_state,omitempty"`
	Usage      Usage     `json:"usage"`
}

// TextContentResponse defines model for TextContentResponse.
type TextContentResponse = JSONResponse

// Timing defines model for Timing.
type Timing struct {
	ByPhase      map[string]int64 `json:"by_phase"`
	TotalSeconds int64            `json:"total_seconds"`
}

// TranscriptResponse defines model for TranscriptResponse.
type TranscriptResponse = JSONResponse

// Usage defines model for Usage.
type Usage struct {
	CostUSD      float64 `json:"cost_usd,omitempty"`
	InputTokens  int     `json:"input_tokens,omitempty"`
	OutputTokens int     `json:"output_tokens,omitempty"`
}

// Warning defines model for Warning.
type Warning struct {
	Code      string `json:"code"`
	FeatureID string `json:"feature_id,omitempty"`
	Message   string `json:"message"`
}

// WorkspaceBrowseResponse defines model for WorkspaceBrowseResponse.
type WorkspaceBrowseResponse = JSONResponse

// ArtifactID defines model for ArtifactID.
type ArtifactID = string

// FeatureAction defines model for FeatureAction.
type FeatureAction string

// FeatureID defines model for FeatureID.
type FeatureID = string

// FeatureSubaction defines model for FeatureSubaction.
type FeatureSubaction string

// Limit defines model for Limit.
type Limit = int64

// LogID defines model for LogID.
type LogID = string

// Offset defines model for Offset.
type Offset = int64

// RunNumber defines model for RunNumber.
type RunNumber = int

// SessionID defines model for SessionID.
type SessionID = string

// TrustedMutationHeader defines model for TrustedMutationHeader.
type TrustedMutationHeader string

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// JSONMutation defines model for JSONMutation.
type JSONMutation map[string]interface{}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// sSEAccessTokenContextKey is the context key for sseAccessToken security scheme
type sSEAccessTokenContextKey string

// PatchRuntimeConfigJSONBody defines parameters for PatchRuntimeConfig.
type PatchRuntimeConfigJSONBody map[string]interface{}

// PatchRuntimeConfigParams defines parameters for PatchRuntimeConfig.
type PatchRuntimeConfigParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient PatchRuntimeConfigParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// PatchRuntimeConfigParamsXAgenticoClient defines parameters for PatchRuntimeConfig.
type PatchRuntimeConfigParamsXAgenticoClient string

// PutRuntimeConfigJSONBody defines parameters for PutRuntimeConfig.
type PutRuntimeConfigJSONBody map[string]interface{}

// PutRuntimeConfigParams defines parameters for PutRuntimeConfig.
type PutRuntimeConfigParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient PutRuntimeConfigParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// PutRuntimeConfigParamsXAgenticoClient defines parameters for PutRuntimeConfig.
type PutRuntimeConfigParamsXAgenticoClient string

// StreamEventsParams defines parameters for StreamEvents.
type StreamEventsParams struct {
	After       uint64 `form:"after,omitempty" json:"after,omitempty"`
	Epoch       string `form:"epoch,omitempty" json:"epoch,omitempty"`
	HeartbeatMs int    `form:"heartbeat_ms,omitempty" json:"heartbeat_ms,omitempty"`
}

// CreateFeatureJSONBody defines parameters for CreateFeature.
type CreateFeatureJSONBody map[string]interface{}

// CreateFeatureParams defines parameters for CreateFeature.
type CreateFeatureParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient CreateFeatureParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// CreateFeatureParamsXAgenticoClient defines parameters for CreateFeature.
type CreateFeatureParamsXAgenticoClient string

// RunFeatureActionJSONBody defines parameters for RunFeatureAction.
type RunFeatureActionJSONBody map[string]interface{}

// RunFeatureActionParams defines parameters for RunFeatureAction.
type RunFeatureActionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient RunFeatureActionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// RunFeatureActionParamsXAgenticoClient defines parameters for RunFeatureAction.
type RunFeatureActionParamsXAgenticoClient string

// RunFeatureActionParamsAction defines parameters for RunFeatureAction.
type RunFeatureActionParamsAction string

// RunFeatureSubactionJSONBody defines parameters for RunFeatureSubaction.
type RunFeatureSubactionJSONBody map[string]interface{}

// RunFeatureSubactionParams defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient RunFeatureSubactionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// RunFeatureSubactionParamsXAgenticoClient defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParamsXAgenticoClient string

// RunFeatureSubactionParamsAction defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParamsAction string

// RunFeatureSubactionParamsSubaction defines parameters for RunFeatureSubaction.
type RunFeatureSubactionParamsSubaction string

// UpdateFeatureConfigJSONBody defines parameters for UpdateFeatureConfig.
type UpdateFeatureConfigJSONBody map[string]interface{}

// UpdateFeatureConfigParams defines parameters for UpdateFeatureConfig.
type UpdateFeatureConfigParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient UpdateFeatureConfigParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// UpdateFeatureConfigParamsXAgenticoClient defines parameters for UpdateFeatureConfig.
type UpdateFeatureConfigParamsXAgenticoClient string

// ToggleInputNotificationsLegacyJSONBody defines parameters for ToggleInputNotificationsLegacy.
type ToggleInputNotificationsLegacyJSONBody map[string]interface{}

// ToggleInputNotificationsLegacyParams defines parameters for ToggleInputNotificationsLegacy.
type ToggleInputNotificationsLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient ToggleInputNotificationsLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// ToggleInputNotificationsLegacyParamsXAgenticoClient defines parameters for ToggleInputNotificationsLegacy.
type ToggleInputNotificationsLegacyParamsXAgenticoClient string

// InterruptFeatureLegacyJSONBody defines parameters for InterruptFeatureLegacy.
type InterruptFeatureLegacyJSONBody map[string]interface{}

// InterruptFeatureLegacyParams defines parameters for InterruptFeatureLegacy.
type InterruptFeatureLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient InterruptFeatureLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// InterruptFeatureLegacyParamsXAgenticoClient defines parameters for InterruptFeatureLegacy.
type InterruptFeatureLegacyParamsXAgenticoClient string

// AnswerNeedUserInputLegacyJSONBody defines parameters for AnswerNeedUserInputLegacy.
type AnswerNeedUserInputLegacyJSONBody map[string]interface{}

// AnswerNeedUserInputLegacyParams defines parameters for AnswerNeedUserInputLegacy.
type AnswerNeedUserInputLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient AnswerNeedUserInputLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// AnswerNeedUserInputLegacyParamsXAgenticoClient defines parameters for AnswerNeedUserInputLegacy.
type AnswerNeedUserInputLegacyParamsXAgenticoClient string

// DraftNeedUserInputLegacyJSONBody defines parameters for DraftNeedUserInputLegacy.
type DraftNeedUserInputLegacyJSONBody map[string]interface{}

// DraftNeedUserInputLegacyParams defines parameters for DraftNeedUserInputLegacy.
type DraftNeedUserInputLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient DraftNeedUserInputLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// DraftNeedUserInputLegacyParamsXAgenticoClient defines parameters for DraftNeedUserInputLegacy.
type DraftNeedUserInputLegacyParamsXAgenticoClient string

// RestartFeatureLegacyJSONBody defines parameters for RestartFeatureLegacy.
type RestartFeatureLegacyJSONBody map[string]interface{}

// RestartFeatureLegacyParams defines parameters for RestartFeatureLegacy.
type RestartFeatureLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient RestartFeatureLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// RestartFeatureLegacyParamsXAgenticoClient defines parameters for RestartFeatureLegacy.
type RestartFeatureLegacyParamsXAgenticoClient string

// ResumeFeatureLegacyJSONBody defines parameters for ResumeFeatureLegacy.
type ResumeFeatureLegacyJSONBody map[string]interface{}

// ResumeFeatureLegacyParams defines parameters for ResumeFeatureLegacy.
type ResumeFeatureLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient ResumeFeatureLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// ResumeFeatureLegacyParamsXAgenticoClient defines parameters for ResumeFeatureLegacy.
type ResumeFeatureLegacyParamsXAgenticoClient string

// SubmitReviewDecisionLegacyJSONBody defines parameters for SubmitReviewDecisionLegacy.
type SubmitReviewDecisionLegacyJSONBody map[string]interface{}

// SubmitReviewDecisionLegacyParams defines parameters for SubmitReviewDecisionLegacy.
type SubmitReviewDecisionLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient SubmitReviewDecisionLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// SubmitReviewDecisionLegacyParamsXAgenticoClient defines parameters for SubmitReviewDecisionLegacy.
type SubmitReviewDecisionLegacyParamsXAgenticoClient string

// GetArtifactContentParams defines parameters for GetArtifactContent.
type GetArtifactContentParams struct {
	Offset Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetRunLogContentParams defines parameters for GetRunLogContent.
type GetRunLogContentParams struct {
	Offset Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// StartFeatureLegacyJSONBody defines parameters for StartFeatureLegacy.
type StartFeatureLegacyJSONBody map[string]interface{}

// StartFeatureLegacyParams defines parameters for StartFeatureLegacy.
type StartFeatureLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient StartFeatureLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// StartFeatureLegacyParamsXAgenticoClient defines parameters for StartFeatureLegacy.
type StartFeatureLegacyParamsXAgenticoClient string

// StopFeatureLegacyJSONBody defines parameters for StopFeatureLegacy.
type StopFeatureLegacyJSONBody map[string]interface{}

// StopFeatureLegacyParams defines parameters for StopFeatureLegacy.
type StopFeatureLegacyParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient StopFeatureLegacyParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// StopFeatureLegacyParamsXAgenticoClient defines parameters for StopFeatureLegacy.
type StopFeatureLegacyParamsXAgenticoClient string

// AnswerPermissionJSONBody defines parameters for AnswerPermission.
type AnswerPermissionJSONBody map[string]interface{}

// AnswerPermissionParams defines parameters for AnswerPermission.
type AnswerPermissionParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient AnswerPermissionParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// AnswerPermissionParamsXAgenticoClient defines parameters for AnswerPermission.
type AnswerPermissionParamsXAgenticoClient string

// AnswerAskUserPromptJSONBody defines parameters for AnswerAskUserPrompt.
type AnswerAskUserPromptJSONBody map[string]interface{}

// AnswerAskUserPromptParams defines parameters for AnswerAskUserPrompt.
type AnswerAskUserPromptParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient AnswerAskUserPromptParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// AnswerAskUserPromptParamsXAgenticoClient defines parameters for AnswerAskUserPrompt.
type AnswerAskUserPromptParamsXAgenticoClient string

// StartChatPromptJSONBody defines parameters for StartChatPrompt.
type StartChatPromptJSONBody map[string]interface{}

// StartChatPromptParams defines parameters for StartChatPrompt.
type StartChatPromptParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient StartChatPromptParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// StartChatPromptParamsXAgenticoClient defines parameters for StartChatPrompt.
type StartChatPromptParamsXAgenticoClient string

// SendHelpPromptJSONBody defines parameters for SendHelpPrompt.
type SendHelpPromptJSONBody map[string]interface{}

// SendHelpPromptParams defines parameters for SendHelpPrompt.
type SendHelpPromptParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient SendHelpPromptParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// SendHelpPromptParamsXAgenticoClient defines parameters for SendHelpPrompt.
type SendHelpPromptParamsXAgenticoClient string

// ExecuteRecoveryActionsJSONBody defines parameters for ExecuteRecoveryActions.
type ExecuteRecoveryActionsJSONBody map[string]interface{}

// ExecuteRecoveryActionsParams defines parameters for ExecuteRecoveryActions.
type ExecuteRecoveryActionsParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient ExecuteRecoveryActionsParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// ExecuteRecoveryActionsParamsXAgenticoClient defines parameters for ExecuteRecoveryActions.
type ExecuteRecoveryActionsParamsXAgenticoClient string

// GetSessionOutputParams defines parameters for GetSessionOutput.
type GetSessionOutputParams struct {
	From  int64 `form:"from,omitempty" json:"from,omitempty"`
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// StreamSessionOutputParams defines parameters for StreamSessionOutput.
type StreamSessionOutputParams struct {
	// From Resume position expressed as a transcript row index (the same index space `/transcript` uses), not a byte offset.
	From int64 `form:"from,omitempty" json:"from,omitempty"`
}

// GetSessionTranscriptParams defines parameters for GetSessionTranscript.
type GetSessionTranscriptParams struct {
	Offset int64 `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ShutdownRuntimeJSONBody defines parameters for ShutdownRuntime.
type ShutdownRuntimeJSONBody map[string]interface{}

// ShutdownRuntimeParams defines parameters for ShutdownRuntime.
type ShutdownRuntimeParams struct {
	// XAgenticoClient CSRF defense-in-depth for local browser-origin mutations. Bearer auth is still required.
	XAgenticoClient ShutdownRuntimeParamsXAgenticoClient `json:"X-Agentico-Client"`
}

// ShutdownRuntimeParamsXAgenticoClient defines parameters for ShutdownRuntime.
type ShutdownRuntimeParamsXAgenticoClient string

// BrowseWorkspaceParams defines parameters for BrowseWorkspace.
type BrowseWorkspaceParams struct {
	Path string `form:"path,omitempty" json:"path,omitempty"`
}

// PatchRuntimeConfigJSONRequestBody defines body for PatchRuntimeConfig for application/json ContentType.
type PatchRuntimeConfigJSONRequestBody PatchRuntimeConfigJSONBody

// PutRuntimeConfigJSONRequestBody defines body for PutRuntimeConfig for application/json ContentType.
type PutRuntimeConfigJSONRequestBody PutRuntimeConfigJSONBody

// CreateFeatureJSONRequestBody defines body for CreateFeature for application/json ContentType.
type CreateFeatureJSONRequestBody CreateFeatureJSONBody

// RunFeatureActionJSONRequestBody defines body for RunFeatureAction for application/json ContentType.
type RunFeatureActionJSONRequestBody RunFeatureActionJSONBody

// RunFeatureSubactionJSONRequestBody defines body for RunFeatureSubaction for application/json ContentType.
type RunFeatureSubactionJSONRequestBody RunFeatureSubactionJSONBody

// UpdateFeatureConfigJSONRequestBody defines body for UpdateFeatureConfig for application/json ContentType.
type UpdateFeatureConfigJSONRequestBody UpdateFeatureConfigJSONBody

// ToggleInputNotificationsLegacyJSONRequestBody defines body for ToggleInputNotificationsLegacy for application/json ContentType.
type ToggleInputNotificationsLegacyJSONRequestBody ToggleInputNotificationsLegacyJSONBody

// InterruptFeatureLegacyJSONRequestBody defines body for InterruptFeatureLegacy for application/json ContentType.
type InterruptFeatureLegacyJSONRequestBody InterruptFeatureLegacyJSONBody

// AnswerNeedUserInputLegacyJSONRequestBody defines body for AnswerNeedUserInputLegacy for application/json ContentType.
type AnswerNeedUserInputLegacyJSONRequestBody AnswerNeedUserInputLegacyJSONBody

// DraftNeedUserInputLegacyJSONRequestBody defines body for DraftNeedUserInputLegacy for application/json ContentType.
type DraftNeedUserInputLegacyJSONRequestBody DraftNeedUserInputLegacyJSONBody

// RestartFeatureLegacyJSONRequestBody defines body for RestartFeatureLegacy for application/json ContentType.
type RestartFeatureLegacyJSONRequestBody RestartFeatureLegacyJSONBody

// ResumeFeatureLegacyJSONRequestBody defines body for ResumeFeatureLegacy for application/json ContentType.
type ResumeFeatureLegacyJSONRequestBody ResumeFeatureLegacyJSONBody

// SubmitReviewDecisionLegacyJSONRequestBody defines body for SubmitReviewDecisionLegacy for application/json ContentType.
type SubmitReviewDecisionLegacyJSONRequestBody SubmitReviewDecisionLegacyJSONBody

// StartFeatureLegacyJSONRequestBody defines body for StartFeatureLegacy for application/json ContentType.
type StartFeatureLegacyJSONRequestBody StartFeatureLegacyJSONBody

// StopFeatureLegacyJSONRequestBody defines body for StopFeatureLegacy for application/json ContentType.
type StopFeatureLegacyJSONRequestBody StopFeatureLegacyJSONBody

// AnswerPermissionJSONRequestBody defines body for AnswerPermission for application/json ContentType.
type AnswerPermissionJSONRequestBody AnswerPermissionJSONBody

// AnswerAskUserPromptJSONRequestBody defines body for AnswerAskUserPrompt for application/json ContentType.
type AnswerAskUserPromptJSONRequestBody AnswerAskUserPromptJSONBody

// StartChatPromptJSONRequestBody defines body for StartChatPrompt for application/json ContentType.
type StartChatPromptJSONRequestBody StartChatPromptJSONBody

// SendHelpPromptJSONRequestBody defines body for SendHelpPrompt for application/json ContentType.
type SendHelpPromptJSONRequestBody SendHelpPromptJSONBody

// ExecuteRecoveryActionsJSONRequestBody defines body for ExecuteRecoveryActions for application/json ContentType.
type ExecuteRecoveryActionsJSONRequestBody ExecuteRecoveryActionsJSONBody

// ShutdownRuntimeJSONRequestBody defines body for ShutdownRuntime for application/json ContentType.
type ShutdownRuntimeJSONRequestBody ShutdownRuntimeJSONBody

// Getter for additional properties for FeatureDetailResponse. Returns the specified
// element and whether it was found
func (a FeatureDetailResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FeatureDetailResponse
func (a *FeatureDetailResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FeatureDetailResponse to handle AdditionalProperties
func (a *FeatureDetailResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.APIVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["feature"]; found {
		err = json.Unmarshal(raw, &a.Feature)
		if err != nil {
			return fmt.Errorf("error reading 'feature': %w", err)
		}
		delete(object, "feature")
	}

	if raw, found := object["meta"]; found {
		err = json.Unmarshal(raw, &a.Meta)
		if err != nil {
			return fmt.Errorf("error reading 'meta': %w", err)
		}
		delete(object, "meta")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FeatureDetailResponse to handle AdditionalProperties
func (a FeatureDetailResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	object["feature"], err = json.Marshal(a.Feature)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'feature': %w", err)
	}

	object["meta"], err = json.Marshal(a.Meta)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'meta': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for FeatureListResponse. Returns the specified
// element and whether it was found
func (a FeatureListResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FeatureListResponse
func (a *FeatureListResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FeatureListResponse to handle AdditionalProperties
func (a *FeatureListResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.APIVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["features"]; found {
		err = json.Unmarshal(raw, &a.Features)
		if err != nil {
			return fmt.Errorf("error reading 'features': %w", err)
		}
		delete(object, "features")
	}

	if raw, found := object["meta"]; found {
		err = json.Unmarshal(raw, &a.Meta)
		if err != nil {
			return fmt.Errorf("error reading 'meta': %w", err)
		}
		delete(object, "meta")
	}

	if raw, found := object["warnings"]; found {
		err = json.Unmarshal(raw, &a.Warnings)
		if err != nil {
			return fmt.Errorf("error reading 'warnings': %w", err)
		}
		delete(object, "warnings")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FeatureListResponse to handle AdditionalProperties
func (a FeatureListResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Features != nil {
		object["features"], err = json.Marshal(a.Features)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'features': %w", err)
		}
	}

	object["meta"], err = json.Marshal(a.Meta)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'meta': %w", err)
	}

	if a.Warnings != nil {
		object["warnings"], err = json.Marshal(a.Warnings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'warnings': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for JSONResponse. Returns the specified
// element and whether it was found
func (a JSONResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for JSONResponse
func (a *JSONResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for JSONResponse to handle AdditionalProperties
func (a *JSONResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.APIVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["meta"]; found {
		err = json.Unmarshal(raw, &a.Meta)
		if err != nil {
			return fmt.Errorf("error reading 'meta': %w", err)
		}
		delete(object, "meta")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for JSONResponse to handle AdditionalProperties
func (a JSONResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	object["meta"], err = json.Marshal(a.Meta)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'meta': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SessionDetailResponse. Returns the specified
// element and whether it was found
func (a SessionDetailResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionDetailResponse
func (a *SessionDetailResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionDetailResponse to handle AdditionalProperties
func (a *SessionDetailResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.APIVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["meta"]; found {
		err = json.Unmarshal(raw, &a.Meta)
		if err != nil {
			return fmt.Errorf("error reading 'meta': %w", err)
		}
		delete(object, "meta")
	}

	if raw, found := object["session"]; found {
		err = json.Unmarshal(raw, &a.Session)
		if err != nil {
			return fmt.Errorf("error reading 'session': %w", err)
		}
		delete(object, "session")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionDetailResponse to handle AdditionalProperties
func (a SessionDetailResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	object["meta"], err = json.Marshal(a.Meta)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'meta': %w", err)
	}

	object["session"], err = json.Marshal(a.Session)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'session': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SessionListResponse. Returns the specified
// element and whether it was found
func (a SessionListResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionListResponse
func (a *SessionListResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionListResponse to handle AdditionalProperties
func (a *SessionListResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.APIVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["meta"]; found {
		err = json.Unmarshal(raw, &a.Meta)
		if err != nil {
			return fmt.Errorf("error reading 'meta': %w", err)
		}
		delete(object, "meta")
	}

	if raw, found := object["sessions"]; found {
		err = json.Unmarshal(raw, &a.Sessions)
		if err != nil {
			return fmt.Errorf("error reading 'sessions': %w", err)
		}
		delete(object, "sessions")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionListResponse to handle AdditionalProperties
func (a SessionListResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	object["meta"], err = json.Marshal(a.Meta)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'meta': %w", err)
	}

	if a.Sessions != nil {
		object["sessions"], err = json.Marshal(a.Sessions)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sessions': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SessionOutputResponse. Returns the specified
// element and whether it was found
func (a SessionOutputResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SessionOutputResponse
func (a *SessionOutputResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SessionOutputResponse to handle AdditionalProperties
func (a *SessionOutputResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.APIVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["done"]; found {
		err = json.Unmarshal(raw, &a.Done)
		if err != nil {
			return fmt.Errorf("error reading 'done': %w", err)
		}
		delete(object, "done")
	}

	if raw, found := object["meta"]; found {
		err = json.Unmarshal(raw, &a.Meta)
		if err != nil {
			return fmt.Errorf("error reading 'meta': %w", err)
		}
		delete(object, "meta")
	}

	if raw, found := object["next_offset"]; found {
		err = json.Unmarshal(raw, &a.NextOffset)
		if err != nil {
			return fmt.Errorf("error reading 'next_offset': %w", err)
		}
		delete(object, "next_offset")
	}

	if raw, found := object["offset"]; found {
		err = json.Unmarshal(raw, &a.Offset)
		if err != nil {
			return fmt.Errorf("error reading 'offset': %w", err)
		}
		delete(object, "offset")
	}

	if raw, found := object["session_id"]; found {
		err = json.Unmarshal(raw, &a.SessionID)
		if err != nil {
			return fmt.Errorf("error reading 'session_id': %w", err)
		}
		delete(object, "session_id")
	}

	if raw, found := object["size"]; found {
		err = json.Unmarshal(raw, &a.Size)
		if err != nil {
			return fmt.Errorf("error reading 'size': %w", err)
		}
		delete(object, "size")
	}

	if raw, found := object["truncated"]; found {
		err = json.Unmarshal(raw, &a.Truncated)
		if err != nil {
			return fmt.Errorf("error reading 'truncated': %w", err)
		}
		delete(object, "truncated")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SessionOutputResponse to handle AdditionalProperties
func (a SessionOutputResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	object["data"], err = json.Marshal(a.Data)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'data': %w", err)
	}

	object["done"], err = json.Marshal(a.Done)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'done': %w", err)
	}

	object["meta"], err = json.Marshal(a.Meta)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'meta': %w", err)
	}

	object["next_offset"], err = json.Marshal(a.NextOffset)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'next_offset': %w", err)
	}

	object["offset"], err = json.Marshal(a.Offset)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'offset': %w", err)
	}

	object["session_id"], err = json.Marshal(a.SessionID)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'session_id': %w", err)
	}

	object["size"], err = json.Marshal(a.Size)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'size': %w", err)
	}

	object["truncated"], err = json.Marshal(a.Truncated)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'truncated': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
